"base_path": /home/rick/Lab/Dev/temp
"preserve_hierarchy": true

files:
  -
    source: 'Localization/*.resx'
    translation: '/Localization/%file_name%.%locale%.resx'
  -
    source: 'Logic/*.resx'
    translation: '/Logic/%file_name%.%locale%.resx'
