#!/bin/bash

# Rename resources, but only for the non-compiled web version

# Comment 2021-Feb-13: Does this do anything at all? It operates in Boneyard? Should that even be there?


cd Boneyard/Site5

find . -iname 'Pages*.resx' -exec rename 's/Pages\.([A-Za-z_\.\-]+)\.resx/Pages_$1\.resx/' {} \;
find . -iname 'Controls*.resx' -exec rename 's/Controls\.([A-Za-z_\.\-]+)\.resx/Controls_$1\.resx/' {} \;

find . -iname '*.cs' -exec perl -pi -e 's/Resources.Pages.([A-Za-z\.]+)/Resources.Pages_$1/g;' {} \;
find . -iname '*.aspx' -exec perl -pi -e 's/Resources.Pages.([A-Za-z\.]+)/Resources.Pages_$1/g;' {} \;
find . -iname '*.cs' -exec perl -pi -e 's/Resources.Controls.([A-Za-z\.]+)/Resources.Controls_$1/g;' {} \;

cd ../..

# Update line count

BuildFiles/Building/scripts/update-kaylock-count

# Restore packages, command line version

mono .nuget/NuGet.exe restore Swarmops.sln

