#!/bin/bash

# Updates LOC count for Swarmops. Run from parent folder,
# like 'BuildFiles/update-loc.sh' for the output to write to right folder.

# Update the LOC count on every sprint deploy.

find . \( -name '*.cs' -o -name '*.as?x' \) | grep -v "External Dep" | grep -v "Site4" | grep -v "Site5" | xargs wc -l > LINESOFCODE
tail -n 1 LINESOFCODE | cut -c 2-7 | xargs printf "%'d" | xargs -I {} sed -i 's/<!--KaylockCount-->.*<!--EndKaylock-->/<!--KaylockCount-->{}<!--EndKaylock-->/' Site/Controls/v5/Base/MainMenu.ascx.cs

