//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swarmops.Logic.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logic_Communications_Transmission_NotificationPayload {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logic_Communications_Transmission_NotificationPayload() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swarmops.Logic.App_GlobalResources.Logic.Communications.Transmission.Notification" +
                            "Payload", typeof(Logic_Communications_Transmission_NotificationPayload).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your requested cash advance with [OrganizationName] for [CurrencyCode] [BudgetAmountFloat], concerning [RequestPurpose], has been attested by the budget owner. It will now proceed to payout to you..
        /// </summary>
        internal static string CashAdvance_Attested_Body {
            get {
                return ResourceManager.GetString("CashAdvance_Attested_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OrganizationName] Cash Advance Attested: [CurrencyCode] [BudgetAmountFloat].
        /// </summary>
        internal static string CashAdvance_Attested_Subject {
            get {
                return ResourceManager.GetString("CashAdvance_Attested_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your requested cash advance with [OrganizationName] for [CurrencyCode] [BudgetAmountFloat], concerning [RequestPurpose], has been DE-attested by the budget owner. This usually indicates some sort of problem with your request.
        ///
        ///Expect more communication from the budget owner to follow on the matter..
        /// </summary>
        internal static string CashAdvance_Deattested_Body {
            get {
                return ResourceManager.GetString("CashAdvance_Deattested_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OrganizationName] Cash Advance DE-attested: [CurrencyCode] [BudgetAmountFloat].
        /// </summary>
        internal static string CashAdvance_Deattested_Subject {
            get {
                return ResourceManager.GetString("CashAdvance_Deattested_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for a cash advance with [OrganizationName] for [CurrencyCode] [BudgetAmountFloat], concerning [RequestPurpose], has been marked as paid out by the organization&apos;s accountants.
        ///
        ///This means you should see the amount on your account shortly..
        /// </summary>
        internal static string CashAdvance_PaidOut_Body {
            get {
                return ResourceManager.GetString("CashAdvance_PaidOut_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OrganizationName] Cash Advance Paid: [CurrencyCode] [BudgetAmountFloat].
        /// </summary>
        internal static string CashAdvance_PaidOut_Subject {
            get {
                return ResourceManager.GetString("CashAdvance_PaidOut_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ConcernedPersonName] has requested a cash advance of [CurrencyCode] [BudgetAmountFloat] for the purpose of [RequestPurpose]. This money is part of your budget, [BudgetName].
        ///
        ///Please log on to Swarmops at [SystemUrl] to attest or deny..
        /// </summary>
        internal static string CashAdvance_Requested_Body {
            get {
                return ResourceManager.GetString("CashAdvance_Requested_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ACTION ITEM) [OrganizationName] Cash Advance Requested: [CurrencyCode] [BudgetAmountFloat] - Attestation Needed.
        /// </summary>
        internal static string CashAdvance_Requested_Subject {
            get {
                return ResourceManager.GetString("CashAdvance_Requested_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your expense claim with [OrganizationName] for [CurrencyCode] [BudgetAmountFloat], concerning [RequestPurpose], has been attested by the budget owner. It will be paid out to you when the receipts are confirmed valid..
        /// </summary>
        internal static string ExpenseClaim_Attested_Body {
            get {
                return ResourceManager.GetString("ExpenseClaim_Attested_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OrganizationName] Expense Claim Attested: [CurrencyCode] [BudgetAmountFloat].
        /// </summary>
        internal static string ExpenseClaim_Attested_Subject {
            get {
                return ResourceManager.GetString("ExpenseClaim_Attested_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ConcernedPersonName] has created an expense claim against the budget of [BudgetName] for the amount of [CurrencyCode] [BudgetAmountFloat]. The claim concerns [RequestPurpose]. You will need to attest this expense claim.
        ///
        ///Please log on to Swarmops at [SystemUrl] to attest or deny..
        /// </summary>
        internal static string ExpenseClaim_Created_Body {
            get {
                return ResourceManager.GetString("ExpenseClaim_Created_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ACTION ITEM) [OrganizationName] Expense Claim Created: [CurrencyCode] [BudgetAmountFloat] - Attestation Needed.
        /// </summary>
        internal static string ExpenseClaim_Created_Subject {
            get {
                return ResourceManager.GetString("ExpenseClaim_Created_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your expense claim with [OrganizationName] for [CurrencyCode] [BudgetAmountFloat], concerning [RequestPurpose], has been DE-attested by the budget owner. This usually indicates some sort of problem with your expense claim.
        ///
        ///Expect more communication from the budget owner to follow on the matter..
        /// </summary>
        internal static string ExpenseClaim_Deattested_Body {
            get {
                return ResourceManager.GetString("ExpenseClaim_Deattested_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OrganizationName] Expense Claim DE-attested: [CurrencyCode] [BudgetAmountFloat].
        /// </summary>
        internal static string ExpenseClaim_Deattested_Subject {
            get {
                return ResourceManager.GetString("ExpenseClaim_Deattested_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your expense claim with [OrganizationName] for [CurrencyCode] [BudgetAmountFloat] concerning [RequestPurpose] has been denied. Expect more communications to follow on what you need to do to file a proper expense claim..
        /// </summary>
        internal static string ExpenseClaim_Denied_Body {
            get {
                return ResourceManager.GetString("ExpenseClaim_Denied_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OrganizationName] Expense Claim DENIED: [CurrencyCode] [BudgetAmountFloat].
        /// </summary>
        internal static string ExpenseClaim_Denied_Subject {
            get {
                return ResourceManager.GetString("ExpenseClaim_Denied_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The receipts for your expense claim with [OrganizationName] for [CurrencyCode] [BudgetAmountFloat], concerning [RequestPurpose], have been DE-validated by the financial record keepers of the organization. This usually indicates some sort of problem with the documentation of your expense claim.
        ///
        ///Expect more communication to follow on the matter. If you don&apos;t hear from record keepers in short time on this matter, do follow up with them..
        /// </summary>
        internal static string ExpenseClaim_Devalidated_Body {
            get {
                return ResourceManager.GetString("ExpenseClaim_Devalidated_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OrganizationName] Expense Claim Receipts DE-validated: [CurrencyCode] [BudgetAmountFloat].
        /// </summary>
        internal static string ExpenseClaim_Devalidated_Subject {
            get {
                return ResourceManager.GetString("ExpenseClaim_Devalidated_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your expense claim with [OrganizationName] for [CurrencyCode] [BudgetAmountFloat], concerning [RequestPurpose], has been marked as paid out by the organization&apos;s accountants.
        ///
        ///This means you should see the amount on your account shortly..
        /// </summary>
        internal static string ExpenseClaim_PaidOut_Body {
            get {
                return ResourceManager.GetString("ExpenseClaim_PaidOut_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OrganizationName] Expense Claim Paid: [CurrencyCode] [BudgetAmountFloat].
        /// </summary>
        internal static string ExpenseClaim_PaidOut_Subject {
            get {
                return ResourceManager.GetString("ExpenseClaim_PaidOut_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The receipts for your expense claim with [OrganizationName] for [CurrencyCode] [BudgetAmountFloat], concerning [RequestPurpose], have been validated by people responsible for keeping the records in order.
        ///
        ///The claim will be paid out to you when the amount has also been attested by the budget owner..
        /// </summary>
        internal static string ExpenseClaim_Validated_Body {
            get {
                return ResourceManager.GetString("ExpenseClaim_Validated_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OrganizationName] Expense Claim Receipts Validated: [CurrencyCode] [BudgetAmountFloat].
        /// </summary>
        internal static string ExpenseClaim_Validated_Subject {
            get {
                return ResourceManager.GetString("ExpenseClaim_Validated_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invoice from [Supplier], concerning [Description], has been filed against your budget of [BudgetName] for the amount of [CurrencyCode] [BudgetAmountFloat]. You must attest this invoice before it proceeds to payout.
        ///
        ///Please log on to Swarmops at [SystemUrl] to attest or deny..
        /// </summary>
        internal static string InboundInvoice_Created_Body {
            get {
                return ResourceManager.GetString("InboundInvoice_Created_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ACTION ITEM) [OrganizationName] Invoice Filed: [CurrencyCode] [BudgetAmountFloat] - Attestation Needed.
        /// </summary>
        internal static string InboundInvoice_Created_Subject {
            get {
                return ResourceManager.GetString("InboundInvoice_Created_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipts have been filed that need validation for their financial processes to continue.
        ///
        ///Please log on to Swarmops at [SystemUrl] to confirm or reject them..
        /// </summary>
        internal static string Receipts_Filed_Body {
            get {
                return ResourceManager.GetString("Receipts_Filed_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ACTION ITEM) [OrganizationName] Receipts Filed - Validation Needed.
        /// </summary>
        internal static string Receipts_Filed_Subject {
            get {
                return ResourceManager.GetString("Receipts_Filed_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swarmops Backend [SwarmopsVersion] on host [HostName] has successfully upgraded the Swarmops database schema to revision [DbVersion].
        ///
        ///This is for information only. You do not need to take action..
        /// </summary>
        internal static string System_DatabaseSchemaUpgraded_Body {
            get {
                return ResourceManager.GetString("System_DatabaseSchemaUpgraded_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swarmops database upgraded.
        /// </summary>
        internal static string System_DatabaseSchemaUpgraded_Subject {
            get {
                return ResourceManager.GetString("System_DatabaseSchemaUpgraded_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception was thrown in Swarmops:
        ///
        ///[EmbeddedPreformattedText].
        /// </summary>
        internal static string System_Exception_Body {
            get {
                return ResourceManager.GetString("System_Exception_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swarmops EXCEPTION!.
        /// </summary>
        internal static string System_Exception_Subject {
            get {
                return ResourceManager.GetString("System_Exception_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swarmops Backend version [SwarmopsVersion] on host [HostName] has successfully started and connected to database and notification frameworks..
        /// </summary>
        internal static string System_Startup_Body {
            get {
                return ResourceManager.GetString("System_Startup_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swarmops Backend operational.
        /// </summary>
        internal static string System_Startup_Subject {
            get {
                return ResourceManager.GetString("System_Startup_Subject", resourceCulture);
            }
        }
    }
}
