//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swarmops.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logic_Financial_PaymentTransferMethodInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logic_Financial_PaymentTransferMethodInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swarmops.Logic.Resources.Logic.Financial.PaymentTransferMethodInfo", typeof(Logic_Financial_PaymentTransferMethodInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Holder Name.
        /// </summary>
        internal static string PaymentTargetField_AccountHolderName {
            get {
                return ResourceManager.GetString("PaymentTargetField_AccountHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string PaymentTargetField_AccountNumber {
            get {
                return ResourceManager.GetString("PaymentTargetField_AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Address.
        /// </summary>
        internal static string PaymentTargetField_BankAddress {
            get {
                return ResourceManager.GetString("PaymentTargetField_BankAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string PaymentTargetField_BankName {
            get {
                return ResourceManager.GetString("PaymentTargetField_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBAN.
        /// </summary>
        internal static string PaymentTargetField_Bban {
            get {
                return ResourceManager.GetString("PaymentTargetField_Bban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIC/Swift Code.
        /// </summary>
        internal static string PaymentTargetField_BicSwift {
            get {
                return ResourceManager.GetString("PaymentTargetField_BicSwift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin Cash Account.
        /// </summary>
        internal static string PaymentTargetField_CashAccount {
            get {
                return ResourceManager.GetString("PaymentTargetField_CashAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing Code.
        /// </summary>
        internal static string PaymentTargetField_ClearingCode {
            get {
                return ResourceManager.GetString("PaymentTargetField_ClearingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptocurrency Address.
        /// </summary>
        internal static string PaymentTargetField_CryptoAddress {
            get {
                return ResourceManager.GetString("PaymentTargetField_CryptoAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giro Number.
        /// </summary>
        internal static string PaymentTargetField_GiroNumber {
            get {
                return ResourceManager.GetString("PaymentTargetField_GiroNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giro Service.
        /// </summary>
        internal static string PaymentTargetField_GiroService {
            get {
                return ResourceManager.GetString("PaymentTargetField_GiroService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        internal static string PaymentTargetField_Iban {
            get {
                return ResourceManager.GetString("PaymentTargetField_Iban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin Cash Account.
        /// </summary>
        internal static string PaymentTargetType_BitcoinCashAccount {
            get {
                return ResourceManager.GetString("PaymentTargetType_BitcoinCashAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic Giro.
        /// </summary>
        internal static string PaymentTargetType_DomesticBankGiro {
            get {
                return ResourceManager.GetString("PaymentTargetType_DomesticBankGiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic Bank Transfer.
        /// </summary>
        internal static string PaymentTargetType_DomesticBankTransfer {
            get {
                return ResourceManager.GetString("PaymentTargetType_DomesticBankTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Bank Transfer.
        /// </summary>
        internal static string PaymentTargetType_InternationalBankTransfer {
            get {
                return ResourceManager.GetString("PaymentTargetType_InternationalBankTransfer", resourceCulture);
            }
        }
    }
}
