//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swarmops.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logic_Swarm_Position {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logic_Swarm_Position() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swarmops.Logic.Resources.Logic.Swarm.Position", typeof(Logic_Swarm_Position).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditor.
        /// </summary>
        internal static string Position_Organization_Auditor {
            get {
                return ResourceManager.GetString("Position_Organization_Auditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditors.
        /// </summary>
        internal static string Position_Organization_Auditor_Plural {
            get {
                return ResourceManager.GetString("Position_Organization_Auditor_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditor Assistant.
        /// </summary>
        internal static string Position_Organization_AuditorAssistant {
            get {
                return ResourceManager.GetString("Position_Organization_AuditorAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditor Assistants.
        /// </summary>
        internal static string Position_Organization_AuditorAssistant_Plural {
            get {
                return ResourceManager.GetString("Position_Organization_AuditorAssistant_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Deputy.
        /// </summary>
        internal static string Position_Organization_BoardDeputy {
            get {
                return ResourceManager.GetString("Position_Organization_BoardDeputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Deputies.
        /// </summary>
        internal static string Position_Organization_BoardDeputy_Plural {
            get {
                return ResourceManager.GetString("Position_Organization_BoardDeputy_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Member.
        /// </summary>
        internal static string Position_Organization_BoardMember {
            get {
                return ResourceManager.GetString("Position_Organization_BoardMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Members.
        /// </summary>
        internal static string Position_Organization_BoardMember_Plural {
            get {
                return ResourceManager.GetString("Position_Organization_BoardMember_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairperson of the Board.
        /// </summary>
        internal static string Position_Organization_Chairperson {
            get {
                return ResourceManager.GetString("Position_Organization_Chairperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairpeople of the Board.
        /// </summary>
        internal static string Position_Organization_Chairperson_Plural {
            get {
                return ResourceManager.GetString("Position_Organization_Chairperson_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairperson Deputy.
        /// </summary>
        internal static string Position_Organization_ChairpersonDeputy {
            get {
                return ResourceManager.GetString("Position_Organization_ChairpersonDeputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairperson Deputies.
        /// </summary>
        internal static string Position_Organization_ChairpersonDeputy_Plural {
            get {
                return ResourceManager.GetString("Position_Organization_ChairpersonDeputy_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sysadmin Assistant (Read-only).
        /// </summary>
        internal static string Position_System_SysadminAssistantReadOnly {
            get {
                return ResourceManager.GetString("Position_System_SysadminAssistantReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sysadmin Assistants (Read-only).
        /// </summary>
        internal static string Position_System_SysadminAssistantReadOnly_Plural {
            get {
                return ResourceManager.GetString("Position_System_SysadminAssistantReadOnly_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Sysadmin.
        /// </summary>
        internal static string Position_System_SysadminMain {
            get {
                return ResourceManager.GetString("Position_System_SysadminMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sysadmin (Read/Write).
        /// </summary>
        internal static string Position_System_SysadminReadWrite {
            get {
                return ResourceManager.GetString("Position_System_SysadminReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sysadmins (Read/Write).
        /// </summary>
        internal static string Position_System_SysadminReadWrite_Plural {
            get {
                return ResourceManager.GetString("Position_System_SysadminReadWrite_Plural", resourceCulture);
            }
        }
    }
}
