//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swarmops.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logic_Swarm_Position {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logic_Swarm_Position() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swarmops.Logic.Resources.Logic.Swarm.Position", typeof(Logic_Swarm_Position).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO Assistant.
        /// </summary>
        internal static string Position_Executive_CeoAssistant {
            get {
                return ResourceManager.GetString("Position_Executive_CeoAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presidential Aide.
        /// </summary>
        internal static string Position_Executive_CeoAssistant_Government {
            get {
                return ResourceManager.GetString("Position_Executive_CeoAssistant_Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presidential Aides.
        /// </summary>
        internal static string Position_Executive_CeoAssistant_Government_Plural {
            get {
                return ResourceManager.GetString("Position_Executive_CeoAssistant_Government_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secretary General Assistant.
        /// </summary>
        internal static string Position_Executive_CeoAssistant_Nonprofit {
            get {
                return ResourceManager.GetString("Position_Executive_CeoAssistant_Nonprofit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secretary General Assistants.
        /// </summary>
        internal static string Position_Executive_CeoAssistant_Nonprofit_Plural {
            get {
                return ResourceManager.GetString("Position_Executive_CeoAssistant_Nonprofit_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO Assistants.
        /// </summary>
        internal static string Position_Executive_CeoAssistant_Plural {
            get {
                return ResourceManager.GetString("Position_Executive_CeoAssistant_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFO Assistant.
        /// </summary>
        internal static string Position_Executive_CfoAssistant {
            get {
                return ResourceManager.GetString("Position_Executive_CfoAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Assistant.
        /// </summary>
        internal static string Position_Executive_CfoAssistant_Nonprofict {
            get {
                return ResourceManager.GetString("Position_Executive_CfoAssistant_Nonprofict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Assistants.
        /// </summary>
        internal static string Position_Executive_CfoAssistant_Nonprofit_Plural {
            get {
                return ResourceManager.GetString("Position_Executive_CfoAssistant_Nonprofit_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFO Assistants.
        /// </summary>
        internal static string Position_Executive_CfoAssistant_Plural {
            get {
                return ResourceManager.GetString("Position_Executive_CfoAssistant_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Executive Officer.
        /// </summary>
        internal static string Position_Executive_ChiefExecutiveOfficer {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefExecutiveOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President.
        /// </summary>
        internal static string Position_Executive_ChiefExecutiveOfficer_Government {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefExecutiveOfficer_Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secretary General.
        /// </summary>
        internal static string Position_Executive_ChiefExecutiveOfficer_Nonprofit {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefExecutiveOfficer_Nonprofit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Financial Officer.
        /// </summary>
        internal static string Position_Executive_ChiefFinancialOfficer {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefFinancialOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minister of Finance.
        /// </summary>
        internal static string Position_Executive_ChiefFinancialOfficer_Government {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefFinancialOfficer_Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasurer.
        /// </summary>
        internal static string Position_Executive_ChiefFinancialOfficer_Nonprofit {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefFinancialOfficer_Nonprofit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Human Resources Officer.
        /// </summary>
        internal static string Position_Executive_ChiefHrOfficer {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefHrOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Community Officer.
        /// </summary>
        internal static string Position_Executive_ChiefHrOfficer_Nonprofit {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefHrOfficer_Nonprofit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Information Officer.
        /// </summary>
        internal static string Position_Executive_ChiefInformationOfficer {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefInformationOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Marketing Officer.
        /// </summary>
        internal static string Position_Executive_ChiefMarketingOfficer {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefMarketingOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minister of Foreign Affairs.
        /// </summary>
        internal static string Position_Executive_ChiefMarketingOfficer_Government {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefMarketingOfficer_Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Outreach Officer.
        /// </summary>
        internal static string Position_Executive_ChiefMarketingOfficer_Nonprofit {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefMarketingOfficer_Nonprofit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Operations Officer.
        /// </summary>
        internal static string Position_Executive_ChiefOperationsOfficer {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefOperationsOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minister of the Interior.
        /// </summary>
        internal static string Position_Executive_ChiefOperationsOfficer_Government {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefOperationsOfficer_Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Activism Officer.
        /// </summary>
        internal static string Position_Executive_ChiefOperationsOfficer_Nonprofit {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefOperationsOfficer_Nonprofit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief of Staff.
        /// </summary>
        internal static string Position_Executive_ChiefStaff {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Technology Officer.
        /// </summary>
        internal static string Position_Executive_ChiefTechnologyOfficer {
            get {
                return ResourceManager.GetString("Position_Executive_ChiefTechnologyOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resources Assistant.
        /// </summary>
        internal static string Position_Executive_HrAssistant {
            get {
                return ResourceManager.GetString("Position_Executive_HrAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Assistant.
        /// </summary>
        internal static string Position_Executive_HrAssistant_Nonprofit {
            get {
                return ResourceManager.GetString("Position_Executive_HrAssistant_Nonprofit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Assistants.
        /// </summary>
        internal static string Position_Executive_HrAssistant_Nonprofit_Plural {
            get {
                return ResourceManager.GetString("Position_Executive_HrAssistant_Nonprofit_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resources Assistants.
        /// </summary>
        internal static string Position_Executive_HrAssistant_Plural {
            get {
                return ResourceManager.GetString("Position_Executive_HrAssistant_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing Assistant.
        /// </summary>
        internal static string Position_Executive_MarketingAssistant {
            get {
                return ResourceManager.GetString("Position_Executive_MarketingAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Affairs Aide.
        /// </summary>
        internal static string Position_Executive_MarketingAssistant_Government {
            get {
                return ResourceManager.GetString("Position_Executive_MarketingAssistant_Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Affairs Aides.
        /// </summary>
        internal static string Position_Executive_MarketingAssistant_Government_Plural {
            get {
                return ResourceManager.GetString("Position_Executive_MarketingAssistant_Government_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outreach Assistant.
        /// </summary>
        internal static string Position_Executive_MarketingAssistant_Nonprofit {
            get {
                return ResourceManager.GetString("Position_Executive_MarketingAssistant_Nonprofit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outreach Assistants.
        /// </summary>
        internal static string Position_Executive_MarketingAssistant_Nonprofit_Plural {
            get {
                return ResourceManager.GetString("Position_Executive_MarketingAssistant_Nonprofit_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing Assistants.
        /// </summary>
        internal static string Position_Executive_MarketingAssistant_Plural {
            get {
                return ResourceManager.GetString("Position_Executive_MarketingAssistant_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President.
        /// </summary>
        internal static string Position_Executive_President {
            get {
                return ResourceManager.GetString("Position_Executive_President", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice President.
        /// </summary>
        internal static string Position_Executive_VicePresident {
            get {
                return ResourceManager.GetString("Position_Executive_VicePresident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deputy Secretary General.
        /// </summary>
        internal static string Position_Executive_VicePresident_Nonprofit {
            get {
                return ResourceManager.GetString("Position_Executive_VicePresident_Nonprofit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deputies Secretary General.
        /// </summary>
        internal static string Position_Executive_VicePresident_Nonprofit_Plural {
            get {
                return ResourceManager.GetString("Position_Executive_VicePresident_Nonprofit_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice Presidents.
        /// </summary>
        internal static string Position_Executive_VicePresident_Plural {
            get {
                return ResourceManager.GetString("Position_Executive_VicePresident_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activism Leader.
        /// </summary>
        internal static string Position_Geographic_ActivismLeader {
            get {
                return ResourceManager.GetString("Position_Geographic_ActivismLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations Leader.
        /// </summary>
        internal static string Position_Geographic_ActivismLeader_Commercial {
            get {
                return ResourceManager.GetString("Position_Geographic_ActivismLeader_Commercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activism Assistant.
        /// </summary>
        internal static string Position_Geographic_ActivismLeaderAssistant {
            get {
                return ResourceManager.GetString("Position_Geographic_ActivismLeaderAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations Assistant.
        /// </summary>
        internal static string Position_Geographic_ActivismLeaderAssistant_Commercial {
            get {
                return ResourceManager.GetString("Position_Geographic_ActivismLeaderAssistant_Commercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations Assistants.
        /// </summary>
        internal static string Position_Geographic_ActivismLeaderAssistant_Commercial_Plural {
            get {
                return ResourceManager.GetString("Position_Geographic_ActivismLeaderAssistant_Commercial_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activism Assistants.
        /// </summary>
        internal static string Position_Geographic_ActivismLeaderAssistant_Plural {
            get {
                return ResourceManager.GetString("Position_Geographic_ActivismLeaderAssistant_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        internal static string Position_Geographic_Assistant {
            get {
                return ResourceManager.GetString("Position_Geographic_Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistants.
        /// </summary>
        internal static string Position_Geographic_Assistant_Plural {
            get {
                return ResourceManager.GetString("Position_Geographic_Assistant_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deputy.
        /// </summary>
        internal static string Position_Geographic_Deputy {
            get {
                return ResourceManager.GetString("Position_Geographic_Deputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deputies.
        /// </summary>
        internal static string Position_Geographic_Deputy_Plural {
            get {
                return ResourceManager.GetString("Position_Geographic_Deputy_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographic Subleaders.
        /// </summary>
        internal static string Position_Geographic_ExpandingSubleaderNode_UxElement {
            get {
                return ResourceManager.GetString("Position_Geographic_ExpandingSubleaderNode_UxElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Leader.
        /// </summary>
        internal static string Position_Geographic_InfoLeader {
            get {
                return ResourceManager.GetString("Position_Geographic_InfoLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Assistant.
        /// </summary>
        internal static string Position_Geographic_InfoLeaderAssistant {
            get {
                return ResourceManager.GetString("Position_Geographic_InfoLeaderAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Assistants.
        /// </summary>
        internal static string Position_Geographic_InfoLeaderAssistant_Plural {
            get {
                return ResourceManager.GetString("Position_Geographic_InfoLeaderAssistant_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        internal static string Position_Geographic_Leader {
            get {
                return ResourceManager.GetString("Position_Geographic_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outreach Leader.
        /// </summary>
        internal static string Position_Geographic_OutreachLeader {
            get {
                return ResourceManager.GetString("Position_Geographic_OutreachLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outreach Assistant.
        /// </summary>
        internal static string Position_Geographic_OutreachLeaderAssistant {
            get {
                return ResourceManager.GetString("Position_Geographic_OutreachLeaderAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outreach Assistants.
        /// </summary>
        internal static string Position_Geographic_OutreachLeaderAssistant_Plural {
            get {
                return ResourceManager.GetString("Position_Geographic_OutreachLeaderAssistant_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swarmcare Leader.
        /// </summary>
        internal static string Position_Geographic_SwarmLeader {
            get {
                return ResourceManager.GetString("Position_Geographic_SwarmLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Care Leader.
        /// </summary>
        internal static string Position_Geographic_SwarmLeader_Commercial {
            get {
                return ResourceManager.GetString("Position_Geographic_SwarmLeader_Commercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swarmcare Assistant.
        /// </summary>
        internal static string Position_Geographic_SwarmLeaderAssistant {
            get {
                return ResourceManager.GetString("Position_Geographic_SwarmLeaderAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Care Assistant.
        /// </summary>
        internal static string Position_Geographic_SwarmLeaderAssistant_Commercial {
            get {
                return ResourceManager.GetString("Position_Geographic_SwarmLeaderAssistant_Commercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Care Assistants.
        /// </summary>
        internal static string Position_Geographic_SwarmLeaderAssistant_Commercial_Plural {
            get {
                return ResourceManager.GetString("Position_Geographic_SwarmLeaderAssistant_Commercial_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swarmcare Assistants.
        /// </summary>
        internal static string Position_Geographic_SwarmLeaderAssistant_Plural {
            get {
                return ResourceManager.GetString("Position_Geographic_SwarmLeaderAssistant_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditor.
        /// </summary>
        internal static string Position_Strategic_Auditor {
            get {
                return ResourceManager.GetString("Position_Strategic_Auditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditors.
        /// </summary>
        internal static string Position_Strategic_Auditor_Plural {
            get {
                return ResourceManager.GetString("Position_Strategic_Auditor_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditor Assistant.
        /// </summary>
        internal static string Position_Strategic_AuditorAssistant {
            get {
                return ResourceManager.GetString("Position_Strategic_AuditorAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditor Assistants.
        /// </summary>
        internal static string Position_Strategic_AuditorAssistant_Plural {
            get {
                return ResourceManager.GetString("Position_Strategic_AuditorAssistant_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditor Deputy.
        /// </summary>
        internal static string Position_Strategic_AuditorDeputy {
            get {
                return ResourceManager.GetString("Position_Strategic_AuditorDeputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditor Deputies.
        /// </summary>
        internal static string Position_Strategic_AuditorDeputy_Plural {
            get {
                return ResourceManager.GetString("Position_Strategic_AuditorDeputy_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairperson of the Board.
        /// </summary>
        internal static string Position_Strategic_BoardChairperson {
            get {
                return ResourceManager.GetString("Position_Strategic_BoardChairperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairpeople of the Board.
        /// </summary>
        internal static string Position_Strategic_BoardChairperson_Plural {
            get {
                return ResourceManager.GetString("Position_Strategic_BoardChairperson_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairperson Deputy.
        /// </summary>
        internal static string Position_Strategic_BoardChairpersonDeputy {
            get {
                return ResourceManager.GetString("Position_Strategic_BoardChairpersonDeputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairperson Deputies.
        /// </summary>
        internal static string Position_Strategic_BoardChairpersonDeputy_Plural {
            get {
                return ResourceManager.GetString("Position_Strategic_BoardChairpersonDeputy_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Deputy.
        /// </summary>
        internal static string Position_Strategic_BoardDeputy {
            get {
                return ResourceManager.GetString("Position_Strategic_BoardDeputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Deputies.
        /// </summary>
        internal static string Position_Strategic_BoardDeputy_Plural {
            get {
                return ResourceManager.GetString("Position_Strategic_BoardDeputy_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Member.
        /// </summary>
        internal static string Position_Strategic_BoardMember {
            get {
                return ResourceManager.GetString("Position_Strategic_BoardMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Members.
        /// </summary>
        internal static string Position_Strategic_BoardMember_Plural {
            get {
                return ResourceManager.GetString("Position_Strategic_BoardMember_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Observer.
        /// </summary>
        internal static string Position_Strategic_Observer {
            get {
                return ResourceManager.GetString("Position_Strategic_Observer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Observers.
        /// </summary>
        internal static string Position_Strategic_Observer_Plural {
            get {
                return ResourceManager.GetString("Position_Strategic_Observer_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sysadmin Assistant (Read-only).
        /// </summary>
        internal static string Position_System_SysadminAssistantReadOnly {
            get {
                return ResourceManager.GetString("Position_System_SysadminAssistantReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sysadmin Assistants (Read-only).
        /// </summary>
        internal static string Position_System_SysadminAssistantReadOnly_Plural {
            get {
                return ResourceManager.GetString("Position_System_SysadminAssistantReadOnly_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Sysadmin.
        /// </summary>
        internal static string Position_System_SysadminMain {
            get {
                return ResourceManager.GetString("Position_System_SysadminMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sysadmin (Read/Write).
        /// </summary>
        internal static string Position_System_SysadminReadWrite {
            get {
                return ResourceManager.GetString("Position_System_SysadminReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sysadmins (Read/Write).
        /// </summary>
        internal static string Position_System_SysadminReadWrite_Plural {
            get {
                return ResourceManager.GetString("Position_System_SysadminReadWrite_Plural", resourceCulture);
            }
        }
    }
}
