//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swarmops.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logic_Financial_Payout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logic_Financial_Payout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swarmops.Logic.Resources.Logic.Financial.Payout", typeof(Logic_Financial_Payout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Advances {0}.
        /// </summary>
        public static string Payout_CashAdvanceIdentities {
            get {
                return ResourceManager.GetString("Payout_CashAdvanceIdentities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Advances {0} for {1}.
        /// </summary>
        public static string Payout_CashAdvanceIdentitiesRecipient {
            get {
                return ResourceManager.GetString("Payout_CashAdvanceIdentitiesRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Advance #{0:N0}.
        /// </summary>
        public static string Payout_CashAdvanceIdentity {
            get {
                return ResourceManager.GetString("Payout_CashAdvanceIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Advance #{0:N0} for {1}.
        /// </summary>
        public static string Payout_CashAdvanceIdentityRecipient {
            get {
                return ResourceManager.GetString("Payout_CashAdvanceIdentityRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Advances {0} Payback.
        /// </summary>
        public static string Payout_CashAdvancePaybackIdentities {
            get {
                return ResourceManager.GetString("Payout_CashAdvancePaybackIdentities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Advance #{0:N0} Payback.
        /// </summary>
        public static string Payout_CashAdvancePaybackIdentity {
            get {
                return ResourceManager.GetString("Payout_CashAdvancePaybackIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses {0}.
        /// </summary>
        public static string Payout_ExpenseClaimIdentities {
            get {
                return ResourceManager.GetString("Payout_ExpenseClaimIdentities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses {0} (minus advances {1}).
        /// </summary>
        public static string Payout_ExpenseClaimIdentitiesLessAdvanceIdentities {
            get {
                return ResourceManager.GetString("Payout_ExpenseClaimIdentitiesLessAdvanceIdentities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses {0} (minus advance #{1:N0}).
        /// </summary>
        public static string Payout_ExpenseClaimIdentitiesLessAdvanceIdentity {
            get {
                return ResourceManager.GetString("Payout_ExpenseClaimIdentitiesLessAdvanceIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Claims {0} by {1}.
        /// </summary>
        public static string Payout_ExpenseClaimIdentitiesRecipient {
            get {
                return ResourceManager.GetString("Payout_ExpenseClaimIdentitiesRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense #{0:N0}.
        /// </summary>
        public static string Payout_ExpenseClaimIdentity {
            get {
                return ResourceManager.GetString("Payout_ExpenseClaimIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense #{0:N0} (minus advances {1}).
        /// </summary>
        public static string Payout_ExpenseClaimIdentityLessAdvanceIdentities {
            get {
                return ResourceManager.GetString("Payout_ExpenseClaimIdentityLessAdvanceIdentities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense #{0:N0} (minus advance #{1:N0}).
        /// </summary>
        public static string Payout_ExpenseClaimIdentityLessAdvanceIdentity {
            get {
                return ResourceManager.GetString("Payout_ExpenseClaimIdentityLessAdvanceIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Claim #{0:N0} by {1}.
        /// </summary>
        public static string Payout_ExpenseClaimIdentityRecipient {
            get {
                return ResourceManager.GetString("Payout_ExpenseClaimIdentityRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Claim #{0:N0}.
        /// </summary>
        public static string Payout_ExpenseClaimLongIdentity {
            get {
                return ResourceManager.GetString("Payout_ExpenseClaimLongIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound Invoice #{0:N0}.
        /// </summary>
        public static string Payout_InboundInvoiceIdentity {
            get {
                return ResourceManager.GetString("Payout_InboundInvoiceIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound Invoice #{0:N0} from {1}.
        /// </summary>
        public static string Payout_InboundInvoiceIdentitySender {
            get {
                return ResourceManager.GetString("Payout_InboundInvoiceIdentitySender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Taxes for {0:yyyy-MMM}.
        /// </summary>
        public static string Payout_SalariesTaxMonth {
            get {
                return ResourceManager.GetString("Payout_SalariesTaxMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salaries {0} for {1:yyyy-MMM}.
        /// </summary>
        public static string Payout_SalaryIdentitiesMonth {
            get {
                return ResourceManager.GetString("Payout_SalaryIdentitiesMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary #{0:N0}.
        /// </summary>
        public static string Payout_SalaryIdentity {
            get {
                return ResourceManager.GetString("Payout_SalaryIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary #{0:N0} for {1:yyyy-MMM}.
        /// </summary>
        public static string Payout_SalaryIdentityMonth {
            get {
                return ResourceManager.GetString("Payout_SalaryIdentityMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary #{0:N0} for {1:yyyy-MMM} for {2}.
        /// </summary>
        public static string Payout_SalaryIdentityMonthRecipient {
            get {
                return ResourceManager.GetString("Payout_SalaryIdentityMonthRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary for {0:yyyy-MMM}.
        /// </summary>
        public static string Payout_SalaryMonth {
            get {
                return ResourceManager.GetString("Payout_SalaryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes for Salaries {0} for {1:yyyy-MMM}.
        /// </summary>
        public static string Payout_SalaryTaxIdentitiesMonth {
            get {
                return ResourceManager.GetString("Payout_SalaryTaxIdentitiesMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes for Salary #{0:N0} for {1:yyyy-MMM}.
        /// </summary>
        public static string Payout_SalaryTaxIdentityMonth {
            get {
                return ResourceManager.GetString("Payout_SalaryTaxIdentityMonth", resourceCulture);
            }
        }
    }
}
