#!/bin/bash

# Directory structure is supposed to be /home/builder/swarmops/packaging/...
# Builds in /home/builder/swarmops/{buildtype}
# Home folder for script is /home/builder/swarmops/packaging

PACKAGENAME=$1
DROPFOLDER=$2
DISTROS=$3
PACKAGE=$4

IFS=',' read -r -a distros <<< "$DISTROS"
unset IFS

for DISTRO in "${distros[@]}"
do
  echo "Packaging for $DISTRO..."

  if [ -e dependencies/$PACKAGE-$DISTRO ]; then
    DEPENDENCIES=$(cat dependencies/$PACKAGE-$DISTRO | tr -d ' \r')
  else
    DEPENDENCIES=$(cat dependencies/$PACKAGE-default | tr -d ' \r')
  fi

  echo "Dependencies: $DEPENDENCIES"

# read -p "Press [Enter] key to make control backup..."

  cp $DROPFOLDER/payload/DEBIAN/control $DROPFOLDER/controlbackup
  sed -i "s/--Dependencies--/$DEPENDENCIES/g" $DROPFOLDER/payload/DEBIAN/control

# read -p "Press [Enter] key to make create checksums..."

  # Calculating new checksums
  echo "Creating MD5 checksum file ($DISTRO)..."
  cd $DROPFOLDER/payload
  ../../scripts/create-md5
  cd ../..

# read -p "Press [Enter] key to make create package..."

  echo "Creating package 'swarmops-$PACKAGENAME-$DISTRO-latest.deb'..."
  if [ -e swarmops-$PACKAGENAME-$DISTRO-latest.deb ]; then
    rm swarmops-$PACKAGENAME-$DISTRO-latest.deb
  fi
  if [ -e swarmops-$PACKAGENAME-latest.deb ]; then
    rm swarmops-$PACKAGENAME-latest.deb
  fi
  fakeroot dpkg-deb --build $DROPFOLDER/payload
  mv $DROPFOLDER/payload.deb swarmops-$PACKAGENAME-$DISTRO-latest.deb
  cp swarmops-$PACKAGENAME-$DISTRO-latest.deb /var/www/packages.swarmops.com

# read -p "Press [Enter] key to add package to repo..."

  echo "Updating repositories ($DISTRO)..."
  cd /var/www/packages.swarmops.com
  reprepro --component contrib includedeb $DISTRO swarmops-$PACKAGENAME-$DISTRO-latest.deb
  cd /home/builder/swarmops/packaging

  echo "Restoring control file, cleaning up ($DISTRO)..."
  cp $DROPFOLDER/controlbackup $DROPFOLDER/payload/DEBIAN/control
  rm $DROPFOLDER/controlbackup
  rm swarmops-$PACKAGENAME-$DISTRO-latest.deb
  rm /var/www/packages.swarmops.com/swarmops-$PACKAGENAME-$DISTRO-latest.deb

done


