#!/bin/bash

if [ "$#" -ne "2" ]; then
    echo "Usage: update-repos <filename> <releasename1,releasename2,...>"
    echo "Example: update-repos internal-latest.deb trusty,xenial,jessie"
    exit 1
fi

cd /var/www/packages.swarmops.com

IFS=',' read -r -a distros <<< "$2"

for debianRelease in "${distros[@]}"
do
    echo "Publishing package for $debianRelease..."
    reprepro --component contrib includedeb $debianRelease $1 	
done

cd /home/builder/swarmops/packaging
unset IFS
