#!/bin/bash

mail -a "From: Swarmops Builder <builds@swarmops.com>" -s "Swarmops SPRINT $SPRINTNAME ($BUILDID) ready." "rick.falkvinge@pirateacademy.eu" < /home/builder/swarmops/packaging/templates/mail-sprint-ready.txt

