//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pages_Swarm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages_Swarm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Pages.Swarm", typeof(Pages_Swarm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid city is required..
        /// </summary>
        internal static string AddPerson_ErrorCity {
            get {
                return ResourceManager.GetString("AddPerson_ErrorCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid date or leave this field empty..
        /// </summary>
        internal static string AddPerson_ErrorDate {
            get {
                return ResourceManager.GetString("AddPerson_ErrorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid email is required..
        /// </summary>
        internal static string AddPerson_ErrorMail {
            get {
                return ResourceManager.GetString("AddPerson_ErrorMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name is required..
        /// </summary>
        internal static string AddPerson_ErrorName {
            get {
                return ResourceManager.GetString("AddPerson_ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid street or P.O. box is required..
        /// </summary>
        internal static string AddPerson_ErrorStreet {
            get {
                return ResourceManager.GetString("AddPerson_ErrorStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography detected.
        /// </summary>
        internal static string AddPerson_GeographyDetected {
            get {
                return ResourceManager.GetString("AddPerson_GeographyDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where you enter new people into the organization. As you register them for a &lt;strong&gt;{0} {1}&lt;/strong&gt; lasting until &lt;strong&gt;{2}&lt;/strong&gt;, they will receive a welcome message with a randomized login password in mail. The local officers will also be notified of the new person, for an opportunity to send them a welcome message..
        /// </summary>
        internal static string AddPerson_Info {
            get {
                return ResourceManager.GetString("AddPerson_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Gender.
        /// </summary>
        internal static string AddPerson_LegalGender {
            get {
                return ResourceManager.GetString("AddPerson_LegalGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The person was successfully added to the organization. A welcome mail has been sent..
        /// </summary>
        internal static string AddPerson_PersonSuccessfullyRegistered {
            get {
                return ResourceManager.GetString("AddPerson_PersonSuccessfullyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical Data.
        /// </summary>
        internal static string AddPerson_StatisticalData {
            get {
                return ResourceManager.GetString("AddPerson_StatisticalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street 1 (or P.O. Box).
        /// </summary>
        internal static string AddPerson_Street1PO {
            get {
                return ResourceManager.GetString("AddPerson_Street1PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street 2 - if applicable.
        /// </summary>
        internal static string AddPerson_Street2 {
            get {
                return ResourceManager.GetString("AddPerson_Street2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}.
        /// </summary>
        internal static string AddPerson_Title {
            get {
                return ResourceManager.GetString("AddPerson_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this to find people in the organization. You can search by geography and by name pattern (&quot;Jo S&quot; will match Joel Sander)..
        /// </summary>
        internal static string ListFindPeople_Info {
            get {
                return ResourceManager.GetString("ListFindPeople_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching People in {0}.
        /// </summary>
        internal static string ListFindPeople_MatchingPeopleInX {
            get {
                return ResourceManager.GetString("ListFindPeople_MatchingPeopleInX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Pattern.
        /// </summary>
        internal static string ListFindPeople_NamePattern {
            get {
                return ResourceManager.GetString("ListFindPeople_NamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List and Find People.
        /// </summary>
        internal static string ListFindPeople_Title {
            get {
                return ResourceManager.GetString("ListFindPeople_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result set contains over a thousand people (display limited to a thousand). Please refine your search?.
        /// </summary>
        internal static string ListFindPeople_TooManyHits {
            get {
                return ResourceManager.GetString("ListFindPeople_TooManyHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Organization ({0}).
        /// </summary>
        internal static string LocalOrganization_Header {
            get {
                return ResourceManager.GetString("LocalOrganization_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Global Organization.
        /// </summary>
        internal static string LocalOrganization_HeaderGlobal {
            get {
                return ResourceManager.GetString("LocalOrganization_HeaderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are your local contacts. (If you have administrative privileges, you may also assign people to these positions.).
        /// </summary>
        internal static string LocalOrganization_Info {
            get {
                return ResourceManager.GetString("LocalOrganization_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Local Organization.
        /// </summary>
        internal static string LocalOrganization_PageTitle {
            get {
                return ResourceManager.GetString("LocalOrganization_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign person....
        /// </summary>
        internal static string Positions_AssignPerson {
            get {
                return ResourceManager.GetString("Positions_AssignPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new position....
        /// </summary>
        internal static string Positions_CreateNewPosition {
            get {
                return ResourceManager.GetString("Positions_CreateNewPosition", resourceCulture);
            }
        }
    }
}
