#!/bin/bash

#Before this, a manual git pull should be done

#Download localizations
cd Localization
./download.sh
cd ..

#Update lines-of-code count
cd ..
BuildFiles/update-kaylock-count
tail -n 1 LINESOFCODE | cut -c 2-7 | xargs printf "%'d" | xargs -I {} sed -i 's/<!--KaylockCount-->.*<!--EndKaylock-->/<!--KaylockCount-->{}<!--EndKaylock-->/' Site/Controls/v5/Base/MainMenu.ascx.cs
cd BuildFiles

#After this, a manual git push should be done
