#!/bin/bash

if [ $(cat /etc/hostname) != 'swarmops-build' ]; then
  echo "This script will only run on the build machine."
  exit 1
fi

# Standard resources files
find -iname '*.??-??.resx' -exec cp {} . \;

# Filipino fil-PH
find -iname '*.fil-PH.resx' -exec cp {} . \;

# Serbian sr-Cyrl-RS, sr-Latn-RS
find -iname '*.sr-????-??.resx' -exec cp {} . \;

