//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string CurrentUserInfo_Logout {
            get {
                return ResourceManager.GetString("CurrentUserInfo_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string CurrentUserInfo_Preferences {
            get {
                return ResourceManager.GetString("CurrentUserInfo_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string CurrentUserInfo_SelectLanguage {
            get {
                return ResourceManager.GetString("CurrentUserInfo_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a default page. The only item available is motion registration for meetings..
        /// </summary>
        internal static string Dashboard_Info_Temporary {
            get {
                return ResourceManager.GetString("Dashboard_Info_Temporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the default page (the dashboard). In time, this will become a really neat page with numbers and graphics and stuff. For now, go to the meeting pages instead..
        /// </summary>
        internal static string Dashboard_Main_Temporary {
            get {
                return ResourceManager.GetString("Dashboard_Main_Temporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard_PageTitle {
            get {
                return ResourceManager.GetString("Dashboard_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a general, unspecified error contacting the Swarmops server. Is the network still operational and the server available?.
        /// </summary>
        internal static string Error_AjaxCallException {
            get {
                return ResourceManager.GetString("Error_AjaxCallException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swarmops does not understand your currency amount. (One thousand money and zero cents are written like &quot;{0:N2}&quot;.) Try again?.
        /// </summary>
        internal static string Error_CurrencyParsing {
            get {
                return ResourceManager.GetString("Error_CurrencyParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems another user beat you to this operation; the database changed while you were looking. Please examine the changed conditions and retry what you were trying to do..
        /// </summary>
        internal static string Error_DatabaseConcurrency {
            get {
                return ResourceManager.GetString("Error_DatabaseConcurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unspecified error attempting to set this value..
        /// </summary>
        internal static string Error_UnspecifiedAjaxSetValue {
            get {
                return ResourceManager.GetString("Error_UnspecifiedAjaxSetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Financial_Account {
            get {
                return ResourceManager.GetString("Financial_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actuals.
        /// </summary>
        internal static string Financial_Actuals {
            get {
                return ResourceManager.GetString("Financial_Actuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actuals (prel).
        /// </summary>
        internal static string Financial_ActualsPreliminary {
            get {
                return ResourceManager.GetString("Financial_ActualsPreliminary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actuals YTD.
        /// </summary>
        internal static string Financial_ActualsToDate {
            get {
                return ResourceManager.GetString("Financial_ActualsToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Balances Are Settled.
        /// </summary>
        internal static string Financial_AllBalancesSettled {
            get {
                return ResourceManager.GetString("Financial_AllBalancesSettled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Financial_Amount {
            get {
                return ResourceManager.GetString("Financial_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        internal static string Financial_AmountVat {
            get {
                return ResourceManager.GetString("Financial_AmountVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Added Tax.
        /// </summary>
        internal static string Financial_AmountVatFull {
            get {
                return ResourceManager.GetString("Financial_AmountVatFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        internal static string Financial_Asset {
            get {
                return ResourceManager.GetString("Financial_Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain.
        /// </summary>
        internal static string Financial_BitcoinChain {
            get {
                return ResourceManager.GetString("Financial_BitcoinChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Financial_BitcoinChain_Cash {
            get {
                return ResourceManager.GetString("Financial_BitcoinChain_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        internal static string Financial_BitcoinChain_Core {
            get {
                return ResourceManager.GetString("Financial_BitcoinChain_Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string Financial_BitcoinChain_Gold {
            get {
                return ResourceManager.GetString("Financial_BitcoinChain_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy.
        /// </summary>
        internal static string Financial_BitcoinChain_Legacy {
            get {
                return ResourceManager.GetString("Financial_BitcoinChain_Legacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeping Account.
        /// </summary>
        internal static string Financial_BookkeepingAccountLong {
            get {
                return ResourceManager.GetString("Financial_BookkeepingAccountLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Financial_BookkeepingAccountShort {
            get {
                return ResourceManager.GetString("Financial_BookkeepingAccountShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        internal static string Financial_Budget {
            get {
                return ResourceManager.GetString("Financial_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        internal static string Financial_CashAdvance {
            get {
                return ResourceManager.GetString("Financial_CashAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Advance #{0:N0} for {1}.
        /// </summary>
        internal static string Financial_CashAdvanceLongSpecificationWithRecipient {
            get {
                return ResourceManager.GetString("Financial_CashAdvanceLongSpecificationWithRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Advance #{0:N0} Payback.
        /// </summary>
        internal static string Financial_CashAdvancePaybackSpecification {
            get {
                return ResourceManager.GetString("Financial_CashAdvancePaybackSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Advances {0} Payback.
        /// </summary>
        internal static string Financial_CashAdvancePaybacksSpecification {
            get {
                return ResourceManager.GetString("Financial_CashAdvancePaybacksSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advances.
        /// </summary>
        internal static string Financial_CashAdvances {
            get {
                return ResourceManager.GetString("Financial_CashAdvances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Advances.
        /// </summary>
        internal static string Financial_CashAdvancesLong {
            get {
                return ResourceManager.GetString("Financial_CashAdvancesLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Advances {0} for {1}.
        /// </summary>
        internal static string Financial_CashAdvancesLongSpecificationWithRecipient {
            get {
                return ResourceManager.GetString("Financial_CashAdvancesLongSpecificationWithRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Advance #{0}.
        /// </summary>
        internal static string Financial_CashAdvanceSpecification {
            get {
                return ResourceManager.GetString("Financial_CashAdvanceSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Advances {0}.
        /// </summary>
        internal static string Financial_CashAdvancesSpecification {
            get {
                return ResourceManager.GetString("Financial_CashAdvancesSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client / Customer.
        /// </summary>
        internal static string Financial_Client {
            get {
                return ResourceManager.GetString("Financial_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string Financial_Cost {
            get {
                return ResourceManager.GetString("Financial_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Balance.
        /// </summary>
        internal static string Financial_CurrentBalance {
            get {
                return ResourceManager.GetString("Financial_CurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liabilities.
        /// </summary>
        internal static string Financial_Debt {
            get {
                return ResourceManager.GetString("Financial_Debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string Financial_DueDate {
            get {
                return ResourceManager.GetString("Financial_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        internal static string Financial_DueDateShort {
            get {
                return ResourceManager.GetString("Financial_DueDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earnings before Interest, Taxes, Depreciation, and Amortization.
        /// </summary>
        internal static string Financial_Ebitda_Long {
            get {
                return ResourceManager.GetString("Financial_Ebitda_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBITDA.
        /// </summary>
        internal static string Financial_Ebitda_Short {
            get {
                return ResourceManager.GetString("Financial_Ebitda_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        internal static string Financial_ExpenseClaim {
            get {
                return ResourceManager.GetString("Financial_ExpenseClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Claim #{0:N0}.
        /// </summary>
        internal static string Financial_ExpenseClaimLongSpecification {
            get {
                return ResourceManager.GetString("Financial_ExpenseClaimLongSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string Financial_ExpenseClaims {
            get {
                return ResourceManager.GetString("Financial_ExpenseClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Claims.
        /// </summary>
        internal static string Financial_ExpenseClaimsLong {
            get {
                return ResourceManager.GetString("Financial_ExpenseClaimsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense #{0:N0}.
        /// </summary>
        internal static string Financial_ExpenseClaimSpecification {
            get {
                return ResourceManager.GetString("Financial_ExpenseClaimSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense #{0:N0} (minus advance #{1:N0}).
        /// </summary>
        internal static string Financial_ExpenseClaimSpecificationLessAdvance {
            get {
                return ResourceManager.GetString("Financial_ExpenseClaimSpecificationLessAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense #{0:N0} (minus advances).
        /// </summary>
        internal static string Financial_ExpenseClaimSpecificationLessAdvances {
            get {
                return ResourceManager.GetString("Financial_ExpenseClaimSpecificationLessAdvances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Claim #{0:N0} by {1}.
        /// </summary>
        internal static string Financial_ExpenseClaimSpecificationWithClaimer {
            get {
                return ResourceManager.GetString("Financial_ExpenseClaimSpecificationWithClaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses {0}.
        /// </summary>
        internal static string Financial_ExpenseClaimsSpecification {
            get {
                return ResourceManager.GetString("Financial_ExpenseClaimsSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses {0} (minus advance #{1}).
        /// </summary>
        internal static string Financial_ExpenseClaimsSpecificationLessAdvance {
            get {
                return ResourceManager.GetString("Financial_ExpenseClaimsSpecificationLessAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses {0} (minus advances).
        /// </summary>
        internal static string Financial_ExpenseClaimsSpecificationLessAdvances {
            get {
                return ResourceManager.GetString("Financial_ExpenseClaimsSpecificationLessAdvances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Claims {0} by {1}.
        /// </summary>
        internal static string Financial_ExpenseClaimsSpecificationWithClaimer {
            get {
                return ResourceManager.GetString("Financial_ExpenseClaimsSpecificationWithClaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Ledger.
        /// </summary>
        internal static string Financial_GeneralLedger {
            get {
                return ResourceManager.GetString("Financial_GeneralLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        internal static string Financial_InboundInvoices {
            get {
                return ResourceManager.GetString("Financial_InboundInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound Invoices.
        /// </summary>
        internal static string Financial_InboundInvoicesLong {
            get {
                return ResourceManager.GetString("Financial_InboundInvoicesLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound Invoice #{0:N0}.
        /// </summary>
        internal static string Financial_InboundInvoiceSpecification {
            get {
                return ResourceManager.GetString("Financial_InboundInvoiceSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound Invoice #{0:N0} from {1}.
        /// </summary>
        internal static string Financial_InboundInvoiceSpecificationWithSender {
            get {
                return ResourceManager.GetString("Financial_InboundInvoiceSpecificationWithSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        internal static string Financial_Income {
            get {
                return ResourceManager.GetString("Financial_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string Financial_InvoiceInbound {
            get {
                return ResourceManager.GetString("Financial_InvoiceInbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string Financial_InvoiceOutbound {
            get {
                return ResourceManager.GetString("Financial_InvoiceOutbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no payments on record.
        /// </summary>
        internal static string Financial_NoPaymentHistory {
            get {
                return ResourceManager.GetString("Financial_NoPaymentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        internal static string Financial_OutboundInvoices {
            get {
                return ResourceManager.GetString("Financial_OutboundInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound Invoices.
        /// </summary>
        internal static string Financial_OutboundInvoicesLong {
            get {
                return ResourceManager.GetString("Financial_OutboundInvoicesLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound Invoice #{0:N0} to {1}.
        /// </summary>
        internal static string Financial_OutboundInvoiceSpecificationWithCustomer {
            get {
                return ResourceManager.GetString("Financial_OutboundInvoiceSpecificationWithCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owed.
        /// </summary>
        internal static string Financial_Owed {
            get {
                return ResourceManager.GetString("Financial_Owed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string Financial_Paid {
            get {
                return ResourceManager.GetString("Financial_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference.
        /// </summary>
        internal static string Financial_Parley {
            get {
                return ResourceManager.GetString("Financial_Parley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment History.
        /// </summary>
        internal static string Financial_PaymentHistory {
            get {
                return ResourceManager.GetString("Financial_PaymentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment #{0:N0}.
        /// </summary>
        internal static string Financial_PaymentSpecification {
            get {
                return ResourceManager.GetString("Financial_PaymentSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout #{0:N0}.
        /// </summary>
        internal static string Financial_PayoutSpecification {
            get {
                return ResourceManager.GetString("Financial_PayoutSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Is Owed.
        /// </summary>
        internal static string Financial_PersonIsOwed {
            get {
                return ResourceManager.GetString("Financial_PersonIsOwed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Owes Amount.
        /// </summary>
        internal static string Financial_PersonOwes {
            get {
                return ResourceManager.GetString("Financial_PersonOwes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Profit/Loss To Date ({0}).
        /// </summary>
        internal static string Financial_ProfitToDate {
            get {
                return ResourceManager.GetString("Financial_ProfitToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Image {0} of {1}.
        /// </summary>
        internal static string Financial_ReceiptSpecification {
            get {
                return ResourceManager.GetString("Financial_ReceiptSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salaries {0} for {1:yyyy-MMM}.
        /// </summary>
        internal static string Financial_SalariesDualSpecification {
            get {
                return ResourceManager.GetString("Financial_SalariesDualSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Taxes for {0:yyyy-MMM}.
        /// </summary>
        internal static string Financial_SalariesTaxSpecification {
            get {
                return ResourceManager.GetString("Financial_SalariesTaxSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string Financial_Salary {
            get {
                return ResourceManager.GetString("Financial_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary #{0:N0} for {1:yyyy-MMM}.
        /// </summary>
        internal static string Financial_SalaryDualSpecification {
            get {
                return ResourceManager.GetString("Financial_SalaryDualSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary #{0:N0} for {1:yyyy-MMM} for {2}.
        /// </summary>
        internal static string Financial_SalaryDualSpecificationWithRecipient {
            get {
                return ResourceManager.GetString("Financial_SalaryDualSpecificationWithRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary #{0:N0}.
        /// </summary>
        internal static string Financial_SalaryIdentity {
            get {
                return ResourceManager.GetString("Financial_SalaryIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary for {0:yyyy-MMM}.
        /// </summary>
        internal static string Financial_SalarySpecification {
            get {
                return ResourceManager.GetString("Financial_SalarySpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes for Salary #{0:N0} for {1:yyyy-MMM}.
        /// </summary>
        internal static string Financial_SalaryTaxDualSpecification {
            get {
                return ResourceManager.GetString("Financial_SalaryTaxDualSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string Financial_Supplier {
            get {
                return ResourceManager.GetString("Financial_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax for salaries {0}.
        /// </summary>
        internal static string Financial_TaxesSpecification {
            get {
                return ResourceManager.GetString("Financial_TaxesSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax for salary #{0}.
        /// </summary>
        internal static string Financial_TaxSpecification {
            get {
                return ResourceManager.GetString("Financial_TaxSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tax Man.
        /// </summary>
        internal static string Financial_TheTaxMan {
            get {
                return ResourceManager.GetString("Financial_TheTaxMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tx#.
        /// </summary>
        internal static string Financial_TransactionIdShort {
            get {
                return ResourceManager.GetString("Financial_TransactionIdShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Type.
        /// </summary>
        internal static string Financial_TransactionTagSetTypeName_CostType {
            get {
                return ResourceManager.GetString("Financial_TransactionTagSetTypeName_CostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Financial_TransactionTagSetTypeName_ProjectName {
            get {
                return ResourceManager.GetString("Financial_TransactionTagSetTypeName_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfirmed Payout.
        /// </summary>
        internal static string Financial_UnconfirmedPayout {
            get {
                return ResourceManager.GetString("Financial_UnconfirmedPayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly result.
        /// </summary>
        internal static string Financial_YearlyResult {
            get {
                return ResourceManager.GetString("Financial_YearlyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Owes You.
        /// </summary>
        internal static string Financial_YouAreOwed {
            get {
                return ResourceManager.GetString("Financial_YouAreOwed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Owe This Amount.
        /// </summary>
        internal static string Financial_YouOwe {
            get {
                return ResourceManager.GetString("Financial_YouOwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YTD.
        /// </summary>
        internal static string Financial_YTD {
            get {
                return ResourceManager.GetString("Financial_YTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero.
        /// </summary>
        internal static string Financial_Zero {
            get {
                return ResourceManager.GetString("Financial_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        internal static string Global_2FA {
            get {
                return ResourceManager.GetString("Global_2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor auth.
        /// </summary>
        internal static string Global_2FA_Short {
            get {
                return ResourceManager.GetString("Global_2FA_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2FA.
        /// </summary>
        internal static string Global_2FA_Shorter {
            get {
                return ResourceManager.GetString("Global_2FA_Shorter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Global_Action {
            get {
                return ResourceManager.GetString("Global_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Global_Add {
            get {
                return ResourceManager.GetString("Global_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Global_Address {
            get {
                return ResourceManager.GetString("Global_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Global_AllYear {
            get {
                return ResourceManager.GetString("Global_AllYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASAP.
        /// </summary>
        internal static string Global_ASAP {
            get {
                return ResourceManager.GetString("Global_ASAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Of Now.
        /// </summary>
        internal static string Global_AsOfNow {
            get {
                return ResourceManager.GetString("Global_AsOfNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Global_Cancel {
            get {
                return ResourceManager.GetString("Global_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change?.
        /// </summary>
        internal static string Global_Change {
            get {
                return ResourceManager.GetString("Global_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Global_City {
            get {
                return ResourceManager.GetString("Global_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click image to enlarge..
        /// </summary>
        internal static string Global_ClickImageToEnlarge {
            get {
                return ResourceManager.GetString("Global_ClickImageToEnlarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Global_Closed {
            get {
                return ResourceManager.GetString("Global_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Global_Confirm {
            get {
                return ResourceManager.GetString("Global_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Global_Country {
            get {
                return ResourceManager.GetString("Global_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Global_Create {
            get {
                return ResourceManager.GetString("Global_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (US).
        /// </summary>
        internal static string Global_CurrentLanguageName_Native {
            get {
                return ResourceManager.GetString("Global_CurrentLanguageName_Native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Global_Custom {
            get {
                return ResourceManager.GetString("Global_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Global_Date {
            get {
                return ResourceManager.GetString("Global_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMMM d.
        /// </summary>
        internal static string Global_DateFormatLongDateMonth {
            get {
                return ResourceManager.GetString("Global_DateFormatLongDateMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMMM d, yyyy.
        /// </summary>
        internal static string Global_DateFormatLongSansWeekday {
            get {
                return ResourceManager.GetString("Global_DateFormatLongSansWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM dd.
        /// </summary>
        internal static string Global_DateFormatShortDateMonth {
            get {
                return ResourceManager.GetString("Global_DateFormatShortDateMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/DD/YYYY.
        /// </summary>
        internal static string Global_DateFormatShortReadable {
            get {
                return ResourceManager.GetString("Global_DateFormatShortReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM d, yyyy.
        /// </summary>
        internal static string Global_DateFormatShortSansWeekday {
            get {
                return ResourceManager.GetString("Global_DateFormatShortSansWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string Global_DateOfBirth {
            get {
                return ResourceManager.GetString("Global_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to define to enable.
        /// </summary>
        internal static string Global_DefineToEnable {
            get {
                return ResourceManager.GetString("Global_DefineToEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Global_Description {
            get {
                return ResourceManager.GetString("Global_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download This.
        /// </summary>
        internal static string Global_DownloadThis {
            get {
                return ResourceManager.GetString("Global_DownloadThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs.
        /// </summary>
        internal static string Global_Dox {
            get {
                return ResourceManager.GetString("Global_Dox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Budget/Account --.
        /// </summary>
        internal static string Global_DropInits_SelectFinancialAccount {
            get {
                return ResourceManager.GetString("Global_DropInits_SelectFinancialAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Organization --.
        /// </summary>
        internal static string Global_DropInits_SelectOrganization {
            get {
                return ResourceManager.GetString("Global_DropInits_SelectOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records.
        /// </summary>
        internal static string Global_EmptySet {
            get {
                return ResourceManager.GetString("Global_EmptySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are entering the &lt;strong&gt;Sandbox&lt;/strong&gt; organization.&lt;br/&gt;&lt;br/&gt;This is a safe environment where you can play around with Swarmops without risking any damage to production data. Have fun all you want, and return to your production environment when you&apos;re done experimenting..
        /// </summary>
        internal static string Global_EnteringSandbox {
            get {
                return ResourceManager.GetString("Global_EnteringSandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action is no longer available..
        /// </summary>
        internal static string Global_Error_Concurrency {
            get {
                return ResourceManager.GetString("Global_Error_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect WebSocket. Live updates will not be available..
        /// </summary>
        internal static string Global_Error_WebsocketFailure {
            get {
                return ResourceManager.GetString("Global_Error_WebsocketFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Global_Female {
            get {
                return ResourceManager.GetString("Global_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be empty..
        /// </summary>
        internal static string Global_FieldCannotBeEmpty {
            get {
                return ResourceManager.GetString("Global_FieldCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload Results.
        /// </summary>
        internal static string Global_FileUploadResults {
            get {
                return ResourceManager.GetString("Global_FileUploadResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        internal static string Global_Flags {
            get {
                return ResourceManager.GetString("Global_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography.
        /// </summary>
        internal static string Global_Geography {
            get {
                return ResourceManager.GetString("Global_Geography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string Global_Go {
            get {
                return ResourceManager.GetString("Global_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go there....
        /// </summary>
        internal static string Global_GoThere {
            get {
                return ResourceManager.GetString("Global_GoThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image {0} of {1}.
        /// </summary>
        internal static string Global_ImageSpecification {
            get {
                return ResourceManager.GetString("Global_ImageSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Global_Item {
            get {
                return ResourceManager.GetString("Global_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Global_Items {
            get {
                return ResourceManager.GetString("Global_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [...loading...].
        /// </summary>
        internal static string Global_LoadingPlaceholder {
            get {
                return ResourceManager.GetString("Global_LoadingPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [...].
        /// </summary>
        internal static string Global_LoadingPlaceholderShort {
            get {
                return ResourceManager.GetString("Global_LoadingPlaceholderShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string Global_Mail {
            get {
                return ResourceManager.GetString("Global_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Global_Male {
            get {
                return ResourceManager.GetString("Global_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min / Max.
        /// </summary>
        internal static string Global_MinMax {
            get {
                return ResourceManager.GetString("Global_MinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - missing -.
        /// </summary>
        internal static string Global_Missing {
            get {
                return ResourceManager.GetString("Global_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Global_Month {
            get {
                return ResourceManager.GetString("Global_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1}.
        /// </summary>
        internal static string Global_MonthXtoY {
            get {
                return ResourceManager.GetString("Global_MonthXtoY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - multiple -.
        /// </summary>
        internal static string Global_Multiple {
            get {
                return ResourceManager.GetString("Global_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string Global_NA {
            get {
                return ResourceManager.GetString("Global_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Applicable.
        /// </summary>
        internal static string Global_NALong {
            get {
                return ResourceManager.GetString("Global_NALong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Global_Name {
            get {
                return ResourceManager.GetString("Global_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Global_No {
            get {
                return ResourceManager.GetString("Global_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No urgent action items. Yay!.
        /// </summary>
        internal static string Global_NoActionItems {
            get {
                return ResourceManager.GetString("Global_NoActionItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no match).
        /// </summary>
        internal static string Global_NoMatch {
            get {
                return ResourceManager.GetString("Global_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody.
        /// </summary>
        internal static string Global_NoOwner {
            get {
                return ResourceManager.GetString("Global_NoOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reason was specified..
        /// </summary>
        internal static string Global_NoReasonGiven {
            get {
                return ResourceManager.GetString("Global_NoReasonGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Global_Notes {
            get {
                return ResourceManager.GetString("Global_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (cancelled, voided, zeroed).
        /// </summary>
        internal static string Global_Nuked {
            get {
                return ResourceManager.GetString("Global_Nuked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Global_Off {
            get {
                return ResourceManager.GetString("Global_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer.
        /// </summary>
        internal static string Global_Officer_Female {
            get {
                return ResourceManager.GetString("Global_Officer_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer.
        /// </summary>
        internal static string Global_Officer_Male {
            get {
                return ResourceManager.GetString("Global_Officer_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer.
        /// </summary>
        internal static string Global_Officer_Neutral {
            get {
                return ResourceManager.GetString("Global_Officer_Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officers.
        /// </summary>
        internal static string Global_Officer_Plural {
            get {
                return ResourceManager.GetString("Global_Officer_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Global_Ok {
            get {
                return ResourceManager.GetString("Global_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string Global_On {
            get {
                return ResourceManager.GetString("Global_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened.
        /// </summary>
        internal static string Global_Opened {
            get {
                return ResourceManager.GetString("Global_Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string Global_Organization {
            get {
                return ResourceManager.GetString("Global_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial.
        /// </summary>
        internal static string Global_Organization_Commercial {
            get {
                return ResourceManager.GetString("Global_Organization_Commercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governmental.
        /// </summary>
        internal static string Global_Organization_Governmental {
            get {
                return ResourceManager.GetString("Global_Organization_Governmental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-profit.
        /// </summary>
        internal static string Global_Organization_Nonprofit {
            get {
                return ResourceManager.GetString("Global_Organization_Nonprofit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Global_Owner {
            get {
                return ResourceManager.GetString("Global_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Global_Phone {
            get {
                return ResourceManager.GetString("Global_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string Global_PostalCode {
            get {
                return ResourceManager.GetString("Global_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        internal static string Global_Proceed {
            get {
                return ResourceManager.GetString("Global_Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing File....
        /// </summary>
        internal static string Global_ProcessingFile {
            get {
                return ResourceManager.GetString("Global_ProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string Global_Progress {
            get {
                return ResourceManager.GetString("Global_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q1.
        /// </summary>
        internal static string Global_Q1 {
            get {
                return ResourceManager.GetString("Global_Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q2.
        /// </summary>
        internal static string Global_Q2 {
            get {
                return ResourceManager.GetString("Global_Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q3.
        /// </summary>
        internal static string Global_Q3 {
            get {
                return ResourceManager.GetString("Global_Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q4.
        /// </summary>
        internal static string Global_Q4 {
            get {
                return ResourceManager.GetString("Global_Q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select one --.
        /// </summary>
        internal static string Global_SelectOne {
            get {
                return ResourceManager.GetString("Global_SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send this to me in mail.
        /// </summary>
        internal static string Global_SendThisInMail {
            get {
                return ResourceManager.GetString("Global_SendThisInMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (several).
        /// </summary>
        internal static string Global_Several_Display {
            get {
                return ResourceManager.GetString("Global_Several_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Several - select --.
        /// </summary>
        internal static string Global_Several_SelectOne {
            get {
                return ResourceManager.GetString("Global_Several_SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Skip.
        /// </summary>
        internal static string Global_SkipNo {
            get {
                return ResourceManager.GetString("Global_SkipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skip this.
        /// </summary>
        internal static string Global_SkipThis {
            get {
                return ResourceManager.GetString("Global_SkipThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Global_SkipYes {
            get {
                return ResourceManager.GetString("Global_SkipYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Global_Submit {
            get {
                return ResourceManager.GetString("Global_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string Global_System {
            get {
                return ResourceManager.GetString("Global_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string Global_Timestamp {
            get {
                return ResourceManager.GetString("Global_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Global_Today {
            get {
                return ResourceManager.GetString("Global_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Global_Total {
            get {
                return ResourceManager.GetString("Global_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter ID.
        /// </summary>
        internal static string Global_TwitterId {
            get {
                return ResourceManager.GetString("Global_TwitterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown or Undisclosed.
        /// </summary>
        internal static string Global_UnknownUndisclosed {
            get {
                return ResourceManager.GetString("Global_UnknownUndisclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Global_Upload {
            get {
                return ResourceManager.GetString("Global_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        internal static string Global_UploadFile {
            get {
                return ResourceManager.GetString("Global_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File To Swarmops.
        /// </summary>
        internal static string Global_UploadFileToSwarmops {
            get {
                return ResourceManager.GetString("Global_UploadFileToSwarmops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file to upload..
        /// </summary>
        internal static string Global_Upload_ErrorSelectFile {
            get {
                return ResourceManager.GetString("Global_Upload_ErrorSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Global_View {
            get {
                return ResourceManager.GetString("Global_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer.
        /// </summary>
        internal static string Global_Volunteer_Female {
            get {
                return ResourceManager.GetString("Global_Volunteer_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer.
        /// </summary>
        internal static string Global_Volunteer_Male {
            get {
                return ResourceManager.GetString("Global_Volunteer_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer.
        /// </summary>
        internal static string Global_Volunteer_Neutral {
            get {
                return ResourceManager.GetString("Global_Volunteer_Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteers.
        /// </summary>
        internal static string Global_Volunteer_Plural {
            get {
                return ResourceManager.GetString("Global_Volunteer_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Global_WizardFinish {
            get {
                return ResourceManager.GetString("Global_WizardFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Global_WizardNext {
            get {
                return ResourceManager.GetString("Global_WizardNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Global_WizardPrevious {
            get {
                return ResourceManager.GetString("Global_WizardPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        internal static string Global_Working {
            get {
                return ResourceManager.GetString("Global_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Global_Year {
            get {
                return ResourceManager.GetString("Global_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year/Month.
        /// </summary>
        internal static string Global_YearMonth {
            get {
                return ResourceManager.GetString("Global_YearMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year {0}.
        /// </summary>
        internal static string Global_YearX {
            get {
                return ResourceManager.GetString("Global_YearX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Global_Yes {
            get {
                return ResourceManager.GetString("Global_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This line item can be automatically scanned by an app..
        /// </summary>
        internal static string IconTooltip_Barcode_Scanning {
            get {
                return ResourceManager.GetString("IconTooltip_Barcode_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Ledgers_Balance {
            get {
                return ResourceManager.GetString("Ledgers_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string Ledgers_Credit {
            get {
                return ResourceManager.GetString("Ledgers_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string Ledgers_Debit {
            get {
                return ResourceManager.GetString("Ledgers_Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;BITID TWO-FACTOR AUTHENTICATION SUCCESSFULLY ENABLED&lt;/strong&gt;&lt;br/&gt;&lt;br/&gt;When logging on to this system from now on, you need to use the BitId application you just used to scan the code..
        /// </summary>
        internal static string Master_BitIdRegistered {
            get {
                return ResourceManager.GetString("Master_BitIdRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitID two-factor authentication has not been enabled..
        /// </summary>
        internal static string Master_BitIdRegister_Fail {
            get {
                return ResourceManager.GetString("Master_BitIdRegister_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan this code to enable BitID.
        /// </summary>
        internal static string Master_BitIdRegister_Header {
            get {
                return ResourceManager.GetString("Master_BitIdRegister_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;What is this?&lt;/h3&gt;
        ///                &lt;p&gt;BitID is a way to log on securely with less hassle than entering a password. Its simplicitly cannot be explained, only experienced, and it is a two-factor authentication since it uses your phone.&lt;/p&gt;
        ///                &lt;h3&gt;Doesn&apos;t this require my phone to be protected also?&lt;/h3&gt;
        ///                &lt;p&gt;Well, yes. It&apos;s your phone and your phone&apos;s access protection. But your phone should always be access protected.&lt;/p&gt;
        ///                &lt;h3&gt;Do I need a mobile app for this?&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Master_BitIdRegister_Sidebar {
            get {
                return ResourceManager.GetString("Master_BitIdRegister_Sidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitID (bitcoin signature) two-factor authentication.
        /// </summary>
        internal static string Master_EditPerson2FAEnable {
            get {
                return ResourceManager.GetString("Master_EditPerson2FAEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitID Two-factor authentication (disabling quarantines login).
        /// </summary>
        internal static string Master_EditPerson2FAEnableProvisioning {
            get {
                return ResourceManager.GetString("Master_EditPerson2FAEnableProvisioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitID two-factor auth.
        /// </summary>
        internal static string Master_EditPerson2FAEnableShort {
            get {
                return ResourceManager.GetString("Master_EditPerson2FAEnableShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;CANNOT PROVISION 2FA&lt;/strong&gt;&lt;br/&gt;&lt;br/&gt;You cannot turn on two-factor authentication for someone else. They must do it by themselves, thereby being alone in having their secret keys..
        /// </summary>
        internal static string Master_EditPerson2FAEnable_CannotProvision {
            get {
                return ResourceManager.GetString("Master_EditPerson2FAEnable_CannotProvision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication has been disabled. You must now log in with a regular password..
        /// </summary>
        internal static string Master_EditPerson2FAEnable_ConfirmingRemovedOwn {
            get {
                return ResourceManager.GetString("Master_EditPerson2FAEnable_ConfirmingRemovedOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication was removed for this user. They must now log in with a regular password..
        /// </summary>
        internal static string Master_EditPerson2FAEnable_ConfirmingRemovedProvision {
            get {
                return ResourceManager.GetString("Master_EditPerson2FAEnable_ConfirmingRemovedProvision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;DISABLE TWO-FACTOR AUTHENTICATION?&lt;/strong&gt;&lt;br/&gt;&lt;br/&gt;This is not recommended. Two-factor authentication significantly raises the security of your account, in addition to making it much easier to log in if you&apos;re using BitID.&lt;br/&gt;&lt;br/&gt;Remove 2FA and fall back to password-only authentication?.
        /// </summary>
        internal static string Master_EditPerson2FAEnable_ConfirmRemoveOwn {
            get {
                return ResourceManager.GetString("Master_EditPerson2FAEnable_ConfirmRemoveOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;REMOVE TWO-FACTOR AUTHENTICATION?&lt;/strong&gt;&lt;br/&gt;&lt;br/&gt;Only do this if you have been requested to turn off 2FA for this user, by this user themselves, &lt;strong&gt;and&lt;/strong&gt; you are absolutely, positively sure that the request came from the person whose security you are disabling (as per the verification policy of the organization).&lt;br/&gt;&lt;br/&gt;Proceed with removing this user&apos;s security? They will fall back to password-only security..
        /// </summary>
        internal static string Master_EditPerson2FAEnable_ConfirmRemoveProvision {
            get {
                return ResourceManager.GetString("Master_EditPerson2FAEnable_ConfirmRemoveProvision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication was not removed and is still active..
        /// </summary>
        internal static string Master_EditPerson2FAEnable_NotRemoved {
            get {
                return ResourceManager.GetString("Master_EditPerson2FAEnable_NotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type current password to enable changes.
        /// </summary>
        internal static string Master_EditPersonCurrentPassword {
            get {
                return ResourceManager.GetString("Master_EditPersonCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Master_EditPersonHeaderAccount {
            get {
                return ResourceManager.GetString("Master_EditPersonHeaderAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Security.
        /// </summary>
        internal static string Master_EditPersonHeaderSecurity {
            get {
                return ResourceManager.GetString("Master_EditPersonHeaderSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Provisioning.
        /// </summary>
        internal static string Master_EditPersonHeaderSecurityProvisioning {
            get {
                return ResourceManager.GetString("Master_EditPersonHeaderSecurityProvisioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set new password.
        /// </summary>
        internal static string Master_EditPersonNewPassword1 {
            get {
                return ResourceManager.GetString("Master_EditPersonNewPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype new password.
        /// </summary>
        internal static string Master_EditPersonNewPassword2 {
            get {
                return ResourceManager.GetString("Master_EditPersonNewPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set new password: The old password is incorrect..
        /// </summary>
        internal static string Master_EditPersonNewPassword_CannotChange_SecurityError {
            get {
                return ResourceManager.GetString("Master_EditPersonNewPassword_CannotChange_SecurityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set new password: The new password is too weak. Use a stronger password..
        /// </summary>
        internal static string Master_EditPersonNewPassword_CannotChange_TooWeak {
            get {
                return ResourceManager.GetString("Master_EditPersonNewPassword_CannotChange_TooWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;PASSWORD CHANGED&lt;/strong&gt;&lt;br/&gt;&lt;br/&gt;You have successfully changed your password. As a security measure, all withdrawals are now in quarantine for the next 48 hours..
        /// </summary>
        internal static string Master_EditPersonNewPassword_Changed {
            get {
                return ResourceManager.GetString("Master_EditPersonNewPassword_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string Master_EditPersonResetPasswordButton {
            get {
                return ResourceManager.GetString("Master_EditPersonResetPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset User Password?.
        /// </summary>
        internal static string Master_EditPersonResetPasswordConfirm_Header {
            get {
                return ResourceManager.GetString("Master_EditPersonResetPasswordConfirm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re resetting a user password. This user will receive a reset link by mail, which they can follow to reset their Swarmops password.&lt;br/&gt;&lt;br/&gt;&lt;strong&gt;Never do this unless specifically asked for assistance with this by the user.&lt;/strong&gt;&lt;br/&gt;&lt;br/&gt;Proceed with password reset procedure?.
        /// </summary>
        internal static string Master_EditPersonResetPasswordConfirm_Text {
            get {
                return ResourceManager.GetString("Master_EditPersonResetPasswordConfirm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail a password-reset link.
        /// </summary>
        internal static string Master_EditPersonResetPasswordLabel {
            get {
                return ResourceManager.GetString("Master_EditPersonResetPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Prohibited.
        /// </summary>
        internal static string Master_EditPersonResetPasswordProhibited_Header {
            get {
                return ResourceManager.GetString("Master_EditPersonResetPasswordProhibited_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user&apos;s mail address was recently changed (less than a week ago). For security reasons, a password reset link cannot and will not be sent to such a newly changed mail address..
        /// </summary>
        internal static string Master_EditPersonResetPasswordProhibited_Text {
            get {
                return ResourceManager.GetString("Master_EditPersonResetPasswordProhibited_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password reset link was sent to this user..
        /// </summary>
        internal static string Master_EditPersonResetPassword_ResetLinkSent {
            get {
                return ResourceManager.GetString("Master_EditPersonResetPassword_ResetLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This doesn&apos;t look like a valid phone number, but we&apos;re storing it as written here nonetheless..
        /// </summary>
        internal static string Master_EditPersonWarning_Phone {
            get {
                return ResourceManager.GetString("Master_EditPersonWarning_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you can, please enable BitID two-factor authentication..
        /// </summary>
        internal static string Master_EditPerson_PleaseEnable2FA {
            get {
                return ResourceManager.GetString("Master_EditPerson_PleaseEnable2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently logged into &lt;strong&gt;{0}&lt;/strong&gt;. Would you like to switch to another organization?.
        /// </summary>
        internal static string Master_SwitchOrganizationDialog {
            get {
                return ResourceManager.GetString("Master_SwitchOrganizationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Sidebar_Actions {
            get {
                return ResourceManager.GetString("Sidebar_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suggested actions at this point..
        /// </summary>
        internal static string Sidebar_Actions_None {
            get {
                return ResourceManager.GetString("Sidebar_Actions_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Sidebar_Help {
            get {
                return ResourceManager.GetString("Sidebar_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Sidebar_Information {
            get {
                return ResourceManager.GetString("Sidebar_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Sidebar_Options {
            get {
                return ResourceManager.GetString("Sidebar_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related.
        /// </summary>
        internal static string Sidebar_Related {
            get {
                return ResourceManager.GetString("Sidebar_Related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To do.
        /// </summary>
        internal static string Sidebar_Todo {
            get {
                return ResourceManager.GetString("Sidebar_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;All Clear:&lt;/strong&gt; There are no urgent action items. Yay!.
        /// </summary>
        internal static string Sidebar_Todo_None {
            get {
                return ResourceManager.GetString("Sidebar_Todo_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action items will go here..
        /// </summary>
        internal static string Sidebar_Todo_Placeholder {
            get {
                return ResourceManager.GetString("Sidebar_Todo_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Person.
        /// </summary>
        internal static string Swarm_AssignedPerson {
            get {
                return ResourceManager.GetString("Swarm_AssignedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Swarm_Position {
            get {
                return ResourceManager.GetString("Swarm_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a name....
        /// </summary>
        internal static string Swarm_TypeName {
            get {
                return ResourceManager.GetString("Swarm_TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a partial name....
        /// </summary>
        internal static string Swarm_TypePartialName {
            get {
                return ResourceManager.GetString("Swarm_TypePartialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to five-year.
        /// </summary>
        internal static string Timespan_FiveYears {
            get {
                return ResourceManager.GetString("Timespan_FiveYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lifetime.
        /// </summary>
        internal static string Timespan_Forever {
            get {
                return ResourceManager.GetString("Timespan_Forever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one-month.
        /// </summary>
        internal static string Timespan_OneMonth {
            get {
                return ResourceManager.GetString("Timespan_OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one-year.
        /// </summary>
        internal static string Timespan_OneYear {
            get {
                return ResourceManager.GetString("Timespan_OneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One day.
        /// </summary>
        internal static string Timespan_Selection_OneDay {
            get {
                return ResourceManager.GetString("Timespan_Selection_OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One month.
        /// </summary>
        internal static string Timespan_Selection_OneMonth {
            get {
                return ResourceManager.GetString("Timespan_Selection_OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One year.
        /// </summary>
        internal static string Timespan_Selection_OneYear {
            get {
                return ResourceManager.GetString("Timespan_Selection_OneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven days.
        /// </summary>
        internal static string Timespan_Selection_SevenDays {
            get {
                return ResourceManager.GetString("Timespan_Selection_SevenDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six months.
        /// </summary>
        internal static string Timespan_Selection_SixMonths {
            get {
                return ResourceManager.GetString("Timespan_Selection_SixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three months.
        /// </summary>
        internal static string Timespan_Selection_ThreeMonths {
            get {
                return ResourceManager.GetString("Timespan_Selection_ThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two days.
        /// </summary>
        internal static string Timespan_Selection_TwoDays {
            get {
                return ResourceManager.GetString("Timespan_Selection_TwoDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two months.
        /// </summary>
        internal static string Timespan_Selection_TwoMonths {
            get {
                return ResourceManager.GetString("Timespan_Selection_TwoMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two weeks.
        /// </summary>
        internal static string Timespan_Selection_TwoWeeks {
            get {
                return ResourceManager.GetString("Timespan_Selection_TwoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two years.
        /// </summary>
        internal static string Timespan_Selection_TwoYears {
            get {
                return ResourceManager.GetString("Timespan_Selection_TwoYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until termination.
        /// </summary>
        internal static string Timespan_Selection_UntilTermination {
            get {
                return ResourceManager.GetString("Timespan_Selection_UntilTermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two-year.
        /// </summary>
        internal static string Timespan_TwoYears {
            get {
                return ResourceManager.GetString("Timespan_TwoYears", resourceCulture);
            }
        }
    }
}
