//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Swarmops.Logic.Resources;

namespace Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Governance {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Governance() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new MonoResourceManager("Pages.Governance");
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved as #{0}-{1}..
        /// </summary>
        public static string AddMotionAmendment_AmendmentSubmittedAs {
            get {
                return ResourceManager.GetString("AddMotionAmendment_AmendmentSubmittedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed decision.
        /// </summary>
        public static string AddMotionAmendment_Decision {
            get {
                return ResourceManager.GetString("AddMotionAmendment_Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Amendment.
        /// </summary>
        public static string AddMotionAmendment_PageTitle {
            get {
                return ResourceManager.GetString("AddMotionAmendment_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Amendment.
        /// </summary>
        public static string AddMotionAmendment_SubmitAmendment {
            get {
                return ResourceManager.GetString("AddMotionAmendment_SubmitAmendment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitter.
        /// </summary>
        public static string AddMotionAmendment_Submitter {
            get {
                return ResourceManager.GetString("AddMotionAmendment_Submitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are submitting an amendment to the motion.
        /// </summary>
        public static string AddMotionAmendment_SubmittingAmendmentInfo {
            get {
                return ResourceManager.GetString("AddMotionAmendment_SubmittingAmendmentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rationale.
        /// </summary>
        public static string AddMotionAmendment_Text {
            get {
                return ResourceManager.GetString("AddMotionAmendment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amendment title.
        /// </summary>
        public static string AddMotionAmendment_Title {
            get {
                return ResourceManager.GetString("AddMotionAmendment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decisions (one per line).
        /// </summary>
        public static string AddMotion_Decisions {
            get {
                return ResourceManager.GetString("AddMotion_Decisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion saved as #{0}..
        /// </summary>
        public static string AddMotion_MotionSubmittedAs {
            get {
                return ResourceManager.GetString("AddMotion_MotionSubmittedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Motion.
        /// </summary>
        public static string AddMotion_PageTitle {
            get {
                return ResourceManager.GetString("AddMotion_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Motion.
        /// </summary>
        public static string AddMotion_SubmitMotion {
            get {
                return ResourceManager.GetString("AddMotion_SubmitMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitter.
        /// </summary>
        public static string AddMotion_Submitter {
            get {
                return ResourceManager.GetString("AddMotion_Submitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are submitting a motion to the meeting.
        /// </summary>
        public static string AddMotion_SubmittingMotionInfo {
            get {
                return ResourceManager.GetString("AddMotion_SubmittingMotionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion rationale.
        /// </summary>
        public static string AddMotion_Text {
            get {
                return ResourceManager.GetString("AddMotion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion title.
        /// </summary>
        public static string AddMotion_Title {
            get {
                return ResourceManager.GetString("AddMotion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong meeting?.
        /// </summary>
        public static string AddMotion_WrongMeeting {
            get {
                return ResourceManager.GetString("AddMotion_WrongMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amended.
        /// </summary>
        public static string ListMotions_Grid_Amended {
            get {
                return ResourceManager.GetString("ListMotions_Grid_Amended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amendments.
        /// </summary>
        public static string ListMotions_Grid_Amendments {
            get {
                return ResourceManager.GetString("ListMotions_Grid_Amendments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carried.
        /// </summary>
        public static string ListMotions_Grid_Carried {
            get {
                return ResourceManager.GetString("ListMotions_Grid_Carried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string ListMotions_Grid_Designation {
            get {
                return ResourceManager.GetString("ListMotions_Grid_Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ListMotions_Grid_Title {
            get {
                return ResourceManager.GetString("ListMotions_Grid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Motions.
        /// </summary>
        public static string ListMotions_PageTitle {
            get {
                return ResourceManager.GetString("ListMotions_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are looking at motions for the meeting.
        /// </summary>
        public static string ListMotions_Sidebar_Info {
            get {
                return ResourceManager.GetString("ListMotions_Sidebar_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit....
        /// </summary>
        public static string ListMotions_SubmitAmendment {
            get {
                return ResourceManager.GetString("ListMotions_SubmitAmendment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propose new amendment to motion.
        /// </summary>
        public static string ViewMotion_AddAmendment {
            get {
                return ResourceManager.GetString("ViewMotion_AddAmendment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amendment.
        /// </summary>
        public static string ViewMotion_Amendment {
            get {
                return ResourceManager.GetString("ViewMotion_Amendment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One amendment.
        /// </summary>
        public static string ViewMotion_AmendmentCountOne {
            get {
                return ResourceManager.GetString("ViewMotion_AmendmentCountOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} amendments.
        /// </summary>
        public static string ViewMotion_AmendmentCountTwoPlus {
            get {
                return ResourceManager.GetString("ViewMotion_AmendmentCountTwoPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No amendments.
        /// </summary>
        public static string ViewMotion_AmendmentCountZero {
            get {
                return ResourceManager.GetString("ViewMotion_AmendmentCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed Change.
        /// </summary>
        public static string ViewMotion_AmendmentProposedChange {
            get {
                return ResourceManager.GetString("ViewMotion_AmendmentProposedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rationale.
        /// </summary>
        public static string ViewMotion_AmendmentText {
            get {
                return ResourceManager.GetString("ViewMotion_AmendmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed decisions.
        /// </summary>
        public static string ViewMotion_DecisionPoints {
            get {
                return ResourceManager.GetString("ViewMotion_DecisionPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion thread.
        /// </summary>
        public static string ViewMotion_Discuss {
            get {
                return ResourceManager.GetString("ViewMotion_Discuss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum thread (posts so far: {0}).
        /// </summary>
        public static string ViewMotion_DiscussLink {
            get {
                return ResourceManager.GetString("ViewMotion_DiscussLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion #{0}.
        /// </summary>
        public static string ViewMotion_MotionDesignation {
            get {
                return ResourceManager.GetString("ViewMotion_MotionDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing Motion.
        /// </summary>
        public static string ViewMotion_PageTitle {
            get {
                return ResourceManager.GetString("ViewMotion_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion rationale.
        /// </summary>
        public static string ViewMotion_Text {
            get {
                return ResourceManager.GetString("ViewMotion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are viewing a motion submitted to the meeting.
        /// </summary>
        public static string ViewMotion_ViewingMotionInfo {
            get {
                return ResourceManager.GetString("ViewMotion_ViewingMotionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board&apos;s Recommendation.
        /// </summary>
        public static string VoteAmendments_BoardRecommendation {
            get {
                return ResourceManager.GetString("VoteAmendments_BoardRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abst..
        /// </summary>
        public static string VoteAmendments_Grid_Abstain {
            get {
                return ResourceManager.GetString("VoteAmendments_Grid_Abstain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board says.
        /// </summary>
        public static string VoteAmendments_Grid_Board {
            get {
                return ResourceManager.GetString("VoteAmendments_Grid_Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string VoteAmendments_Grid_Change {
            get {
                return ResourceManager.GetString("VoteAmendments_Grid_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision.
        /// </summary>
        public static string VoteAmendments_Grid_Decision {
            get {
                return ResourceManager.GetString("VoteAmendments_Grid_Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string VoteAmendments_Grid_Designation {
            get {
                return ResourceManager.GetString("VoteAmendments_Grid_Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string VoteAmendments_Grid_No {
            get {
                return ResourceManager.GetString("VoteAmendments_Grid_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rationale.
        /// </summary>
        public static string VoteAmendments_Grid_Rationale {
            get {
                return ResourceManager.GetString("VoteAmendments_Grid_Rationale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rec..
        /// </summary>
        public static string VoteAmendments_Grid_Recommend {
            get {
                return ResourceManager.GetString("VoteAmendments_Grid_Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string VoteAmendments_Grid_Text {
            get {
                return ResourceManager.GetString("VoteAmendments_Grid_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text / Title.
        /// </summary>
        public static string VoteAmendments_Grid_TitleText {
            get {
                return ResourceManager.GetString("VoteAmendments_Grid_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string VoteAmendments_Grid_Yes {
            get {
                return ResourceManager.GetString("VoteAmendments_Grid_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amendments for {0}.
        /// </summary>
        public static string VoteAmendments_Header {
            get {
                return ResourceManager.GetString("VoteAmendments_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote for suggested changes (amendments) to motions. If pass, they change the motion. In the next round, we will vote for the resulting motions. The individual amendments are listed under each motion, and there are additional details under each motion and amendment. Select a voting recommendation if you like..
        /// </summary>
        public static string VoteAmendments_Info {
            get {
                return ResourceManager.GetString("VoteAmendments_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote on Amendments.
        /// </summary>
        public static string VoteAmendments_PageTitle {
            get {
                return ResourceManager.GetString("VoteAmendments_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---.
        /// </summary>
        public static string VoteAmendments_Recommend_Abstain {
            get {
                return ResourceManager.GetString("VoteAmendments_Recommend_Abstain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string VoteAmendments_Recommend_No {
            get {
                return ResourceManager.GetString("VoteAmendments_Recommend_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string VoteAmendments_Recommend_Yes {
            get {
                return ResourceManager.GetString("VoteAmendments_Recommend_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m Done, Submit My Vote.
        /// </summary>
        public static string VoteAmendments_SaveVote {
            get {
                return ResourceManager.GetString("VoteAmendments_SaveVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Vote In Test Meeting.
        /// </summary>
        public static string VoteAmendments_SaveVote_Temp {
            get {
                return ResourceManager.GetString("VoteAmendments_SaveVote_Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select recommendations....
        /// </summary>
        public static string VoteAmendments_SelectRecommendation {
            get {
                return ResourceManager.GetString("VoteAmendments_SelectRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create voting list?.
        /// </summary>
        public static string Vote_CreateVotingList {
            get {
                return ResourceManager.GetString("Vote_CreateVotingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create voting list for amendments.
        /// </summary>
        public static string Vote_CreateVotingList_Amendments {
            get {
                return ResourceManager.GetString("Vote_CreateVotingList_Amendments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create voting list for an election.
        /// </summary>
        public static string Vote_CreateVotingList_Elections {
            get {
                return ResourceManager.GetString("Vote_CreateVotingList_Elections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create voting list for motions.
        /// </summary>
        public static string Vote_CreateVotingList_Motions {
            get {
                return ResourceManager.GetString("Vote_CreateVotingList_Motions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes, {0} holds meetings. During these meetings, members get to vote. This is a list of what you may vote on. You can also create a voting list that serves as a recommendation to others..
        /// </summary>
        public static string Vote_Info {
            get {
                return ResourceManager.GetString("Vote_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elections.
        /// </summary>
        public static string Vote_MeetingElections {
            get {
                return ResourceManager.GetString("Vote_MeetingElections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motions.
        /// </summary>
        public static string Vote_Motions {
            get {
                return ResourceManager.GetString("Vote_Motions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Amendments.
        /// </summary>
        public static string Vote_MotionVotingMotionAmendments {
            get {
                return ResourceManager.GetString("Vote_MotionVotingMotionAmendments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motions.
        /// </summary>
        public static string Vote_MotionVotingMotions {
            get {
                return ResourceManager.GetString("Vote_MotionVotingMotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not open yet.
        /// </summary>
        public static string Vote_NotOpenedYet {
            get {
                return ResourceManager.GetString("Vote_NotOpenedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens {0:yyyy-MMM-dd}..
        /// </summary>
        public static string Vote_OpensOnDate {
            get {
                return ResourceManager.GetString("Vote_OpensOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string Vote_PageTitle {
            get {
                return ResourceManager.GetString("Vote_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points of Order.
        /// </summary>
        public static string Vote_PointsOfOrder {
            get {
                return ResourceManager.GetString("Vote_PointsOfOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No points of order at the moment..
        /// </summary>
        public static string Vote_PointsOfOrderTemp {
            get {
                return ResourceManager.GetString("Vote_PointsOfOrderTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote here.
        /// </summary>
        public static string Vote_VoteHere {
            get {
                return ResourceManager.GetString("Vote_VoteHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote on {0:N0} amendments:.
        /// </summary>
        public static string Vote_VoteOnAmendments {
            get {
                return ResourceManager.GetString("Vote_VoteOnAmendments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote on {0:N0} motions:.
        /// </summary>
        public static string Vote_VoteOnMotions {
            get {
                return ResourceManager.GetString("Vote_VoteOnMotions", resourceCulture);
            }
        }
    }
}
