//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Pages.Swarm {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lol_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lol_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Pages.Swarm.lol_US", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555518:0crwdne6555518:0.
        /// </summary>
        internal static string AddPerson_ErrorCity {
            get {
                return ResourceManager.GetString("AddPerson_ErrorCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555535:0crwdne6555535:0.
        /// </summary>
        internal static string AddPerson_ErrorDate {
            get {
                return ResourceManager.GetString("AddPerson_ErrorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555519:0crwdne6555519:0.
        /// </summary>
        internal static string AddPerson_ErrorMail {
            get {
                return ResourceManager.GetString("AddPerson_ErrorMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555520:0crwdne6555520:0.
        /// </summary>
        internal static string AddPerson_ErrorName {
            get {
                return ResourceManager.GetString("AddPerson_ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555521:0crwdne6555521:0.
        /// </summary>
        internal static string AddPerson_ErrorStreet {
            get {
                return ResourceManager.GetString("AddPerson_ErrorStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555522:0crwdne6555522:0.
        /// </summary>
        internal static string AddPerson_GeographyDetected {
            get {
                return ResourceManager.GetString("AddPerson_GeographyDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555523:0{0}crwdnd6555523:0{1}crwdnd6555523:0{2}crwdne6555523:0.
        /// </summary>
        internal static string AddPerson_Info {
            get {
                return ResourceManager.GetString("AddPerson_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555524:0crwdne6555524:0.
        /// </summary>
        internal static string AddPerson_LegalGender {
            get {
                return ResourceManager.GetString("AddPerson_LegalGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555536:0crwdne6555536:0.
        /// </summary>
        internal static string AddPerson_PersonSuccessfullyRegistered {
            get {
                return ResourceManager.GetString("AddPerson_PersonSuccessfullyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555526:0crwdne6555526:0.
        /// </summary>
        internal static string AddPerson_StatisticalData {
            get {
                return ResourceManager.GetString("AddPerson_StatisticalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555527:0crwdne6555527:0.
        /// </summary>
        internal static string AddPerson_Street1PO {
            get {
                return ResourceManager.GetString("AddPerson_Street1PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555528:0crwdne6555528:0.
        /// </summary>
        internal static string AddPerson_Street2 {
            get {
                return ResourceManager.GetString("AddPerson_Street2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555529:0{0}crwdne6555529:0.
        /// </summary>
        internal static string AddPerson_Title {
            get {
                return ResourceManager.GetString("AddPerson_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555530:0crwdne6555530:0.
        /// </summary>
        internal static string ListFindPeople_Info {
            get {
                return ResourceManager.GetString("ListFindPeople_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555531:0{0}crwdne6555531:0.
        /// </summary>
        internal static string ListFindPeople_MatchingPeopleInX {
            get {
                return ResourceManager.GetString("ListFindPeople_MatchingPeopleInX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555532:0crwdne6555532:0.
        /// </summary>
        internal static string ListFindPeople_NamePattern {
            get {
                return ResourceManager.GetString("ListFindPeople_NamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555533:0crwdne6555533:0.
        /// </summary>
        internal static string ListFindPeople_Title {
            get {
                return ResourceManager.GetString("ListFindPeople_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555534:0crwdne6555534:0.
        /// </summary>
        internal static string ListFindPeople_TooManyHits {
            get {
                return ResourceManager.GetString("ListFindPeople_TooManyHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556249:0{0}crwdne6556249:0.
        /// </summary>
        internal static string LocalOrganization_Header {
            get {
                return ResourceManager.GetString("LocalOrganization_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556250:0crwdne6556250:0.
        /// </summary>
        internal static string LocalOrganization_HeaderGlobal {
            get {
                return ResourceManager.GetString("LocalOrganization_HeaderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556251:0crwdne6556251:0.
        /// </summary>
        internal static string LocalOrganization_Info {
            get {
                return ResourceManager.GetString("LocalOrganization_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556252:0crwdne6556252:0.
        /// </summary>
        internal static string LocalOrganization_PageTitle {
            get {
                return ResourceManager.GetString("LocalOrganization_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555818:0crwdne6555818:0.
        /// </summary>
        internal static string Positions_AssignPerson {
            get {
                return ResourceManager.GetString("Positions_AssignPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555819:0crwdne6555819:0.
        /// </summary>
        internal static string Positions_CreateNewPosition {
            get {
                return ResourceManager.GetString("Positions_CreateNewPosition", resourceCulture);
            }
        }
    }
}
