//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Pages.Financial {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lol_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lol_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Pages.Financial.lol_US", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563424:0{0:N0}crwdnd6563424:0{1}crwdnd6563424:0{3:N2}crwdne6563424:0.
        /// </summary>
        internal static string AttestCosts_AdvanceAttested {
            get {
                return ResourceManager.GetString("AttestCosts_AdvanceAttested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563426:0{0:N0}crwdnd6563426:0{1}crwdne6563426:0.
        /// </summary>
        internal static string AttestCosts_AdvanceDeattested {
            get {
                return ResourceManager.GetString("AttestCosts_AdvanceDeattested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563428:0{0}crwdne6563428:0.
        /// </summary>
        internal static string AttestCosts_BudgetIsEmpty {
            get {
                return ResourceManager.GetString("AttestCosts_BudgetIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563430:0crwdne6563430:0.
        /// </summary>
        internal static string AttestCosts_CannotAttestNegative {
            get {
                return ResourceManager.GetString("AttestCosts_CannotAttestNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563432:0crwdne6563432:0.
        /// </summary>
        internal static string AttestCosts_CannotAttestZero {
            get {
                return ResourceManager.GetString("AttestCosts_CannotAttestZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556115:0crwdne6556115:0.
        /// </summary>
        internal static string AttestCosts_Error_CantRebudgetSalary {
            get {
                return ResourceManager.GetString("AttestCosts_Error_CantRebudgetSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556116:0crwdne6556116:0.
        /// </summary>
        internal static string AttestCosts_Error_InvalidAmountRetry {
            get {
                return ResourceManager.GetString("AttestCosts_Error_InvalidAmountRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556117:0crwdne6556117:0.
        /// </summary>
        internal static string AttestCosts_Error_PleaseSelectBudget {
            get {
                return ResourceManager.GetString("AttestCosts_Error_PleaseSelectBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563434:0{0:N0}crwdnd6563434:0{1}crwdnd6563434:0{2}crwdnd6563434:0{3:N2}crwdne6563434:0.
        /// </summary>
        internal static string AttestCosts_ExpenseAttested {
            get {
                return ResourceManager.GetString("AttestCosts_ExpenseAttested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563474:0{0:N0}crwdnd6563474:0{1}crwdne6563474:0.
        /// </summary>
        internal static string AttestCosts_ExpenseDeattested {
            get {
                return ResourceManager.GetString("AttestCosts_ExpenseDeattested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555277:0crwdne6555277:0.
        /// </summary>
        internal static string AttestCosts_GridHeader_Action {
            get {
                return ResourceManager.GetString("AttestCosts_GridHeader_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555278:0crwdne6555278:0.
        /// </summary>
        internal static string AttestCosts_GridHeader_Beneficiary {
            get {
                return ResourceManager.GetString("AttestCosts_GridHeader_Beneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555279:0crwdne6555279:0.
        /// </summary>
        internal static string AttestCosts_GridHeader_Budget {
            get {
                return ResourceManager.GetString("AttestCosts_GridHeader_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555280:0crwdne6555280:0.
        /// </summary>
        internal static string AttestCosts_GridHeader_Description {
            get {
                return ResourceManager.GetString("AttestCosts_GridHeader_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555281:0crwdne6555281:0.
        /// </summary>
        internal static string AttestCosts_GridHeader_Docs {
            get {
                return ResourceManager.GetString("AttestCosts_GridHeader_Docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555282:0crwdne6555282:0.
        /// </summary>
        internal static string AttestCosts_GridHeader_Item {
            get {
                return ResourceManager.GetString("AttestCosts_GridHeader_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555283:0crwdne6555283:0.
        /// </summary>
        internal static string AttestCosts_GridHeader_Requested {
            get {
                return ResourceManager.GetString("AttestCosts_GridHeader_Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563436:0crwdne6563436:0.
        /// </summary>
        internal static string AttestCosts_Header_CostsAwaitingAttestation {
            get {
                return ResourceManager.GetString("AttestCosts_Header_CostsAwaitingAttestation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563438:0crwdne6563438:0.
        /// </summary>
        internal static string AttestCosts_Info {
            get {
                return ResourceManager.GetString("AttestCosts_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563440:0{0:N0}crwdnd6563440:0{1}crwdnd6563440:0{2}crwdnd6563440:0{3:N2}crwdne6563440:0.
        /// </summary>
        internal static string AttestCosts_InvoiceAttested {
            get {
                return ResourceManager.GetString("AttestCosts_InvoiceAttested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563442:0{0:N0}crwdnd6563442:0{1}crwdne6563442:0.
        /// </summary>
        internal static string AttestCosts_InvoiceDeattested {
            get {
                return ResourceManager.GetString("AttestCosts_InvoiceDeattested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563444:0crwdne6563444:0.
        /// </summary>
        internal static string AttestCosts_Modal_ButtonAmount {
            get {
                return ResourceManager.GetString("AttestCosts_Modal_ButtonAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563446:0crwdne6563446:0.
        /// </summary>
        internal static string AttestCosts_Modal_ButtonCorrect {
            get {
                return ResourceManager.GetString("AttestCosts_Modal_ButtonCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556092:0crwdne6556092:0.
        /// </summary>
        internal static string AttestCosts_Modal_ButtonDeny {
            get {
                return ResourceManager.GetString("AttestCosts_Modal_ButtonDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556093:0crwdne6556093:0.
        /// </summary>
        internal static string AttestCosts_Modal_ButtonRebudget {
            get {
                return ResourceManager.GetString("AttestCosts_Modal_ButtonRebudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556094:0crwdne6556094:0.
        /// </summary>
        internal static string AttestCosts_Modal_DenyTextPlaceholder {
            get {
                return ResourceManager.GetString("AttestCosts_Modal_DenyTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556767:0crwdne6556767:0.
        /// </summary>
        internal static string AttestCosts_Modal_DescribeCorrectNoVat {
            get {
                return ResourceManager.GetString("AttestCosts_Modal_DescribeCorrectNoVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556095:0{0}crwdne6556095:0.
        /// </summary>
        internal static string AttestCosts_Modal_DescribeOptionAmount {
            get {
                return ResourceManager.GetString("AttestCosts_Modal_DescribeOptionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556119:0{0}crwdne6556119:0.
        /// </summary>
        internal static string AttestCosts_Modal_DescribeOptionCorrect {
            get {
                return ResourceManager.GetString("AttestCosts_Modal_DescribeOptionCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556096:0crwdne6556096:0.
        /// </summary>
        internal static string AttestCosts_Modal_DescribeOptionDeny {
            get {
                return ResourceManager.GetString("AttestCosts_Modal_DescribeOptionDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556097:0crwdne6556097:0.
        /// </summary>
        internal static string AttestCosts_Modal_DescribeOptionRebudget {
            get {
                return ResourceManager.GetString("AttestCosts_Modal_DescribeOptionRebudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563448:0crwdne6563448:0.
        /// </summary>
        internal static string AttestCosts_Modal_Header {
            get {
                return ResourceManager.GetString("AttestCosts_Modal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563450:0crwdne6563450:0.
        /// </summary>
        internal static string AttestCosts_Modal_RadioOptionAmount {
            get {
                return ResourceManager.GetString("AttestCosts_Modal_RadioOptionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563452:0crwdne6563452:0.
        /// </summary>
        internal static string AttestCosts_Modal_RadioOptionCorrect {
            get {
                return ResourceManager.GetString("AttestCosts_Modal_RadioOptionCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563454:0crwdne6563454:0.
        /// </summary>
        internal static string AttestCosts_Modal_RadioOptionDeny {
            get {
                return ResourceManager.GetString("AttestCosts_Modal_RadioOptionDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556101:0crwdne6556101:0.
        /// </summary>
        internal static string AttestCosts_Modal_RadioOptionRebudget {
            get {
                return ResourceManager.GetString("AttestCosts_Modal_RadioOptionRebudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556102:0crwdne6556102:0.
        /// </summary>
        internal static string AttestCosts_Modal_WhatIsProblem {
            get {
                return ResourceManager.GetString("AttestCosts_Modal_WhatIsProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563456:0crwdne6563456:0.
        /// </summary>
        internal static string AttestCosts_OutOfBudget {
            get {
                return ResourceManager.GetString("AttestCosts_OutOfBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563458:0{0}crwdnd6563458:0{1:N2}crwdnd6563458:0{2}crwdne6563458:0.
        /// </summary>
        internal static string AttestCosts_OutOfBudgetPrecise {
            get {
                return ResourceManager.GetString("AttestCosts_OutOfBudgetPrecise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563460:0crwdne6563460:0.
        /// </summary>
        internal static string AttestCosts_OverdraftConfirm {
            get {
                return ResourceManager.GetString("AttestCosts_OverdraftConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556136:0crwdne6556136:0.
        /// </summary>
        internal static string AttestCosts_OverdraftConfirmNo {
            get {
                return ResourceManager.GetString("AttestCosts_OverdraftConfirmNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556137:0crwdne6556137:0.
        /// </summary>
        internal static string AttestCosts_OverdraftConfirmYes {
            get {
                return ResourceManager.GetString("AttestCosts_OverdraftConfirmYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556138:0crwdne6556138:0.
        /// </summary>
        internal static string AttestCosts_Overdrafted {
            get {
                return ResourceManager.GetString("AttestCosts_Overdrafted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563462:0crwdne6563462:0.
        /// </summary>
        internal static string AttestCosts_PageTitle {
            get {
                return ResourceManager.GetString("AttestCosts_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563464:0{0:N0}crwdnd6563464:0{1}crwdnd6563464:0{3:N2}crwdne6563464:0.
        /// </summary>
        internal static string AttestCosts_ParleyAttested {
            get {
                return ResourceManager.GetString("AttestCosts_ParleyAttested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563466:0{0:N0}crwdnd6563466:0{1}crwdne6563466:0.
        /// </summary>
        internal static string AttestCosts_ParleyDeattested {
            get {
                return ResourceManager.GetString("AttestCosts_ParleyDeattested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555291:0{0:N0}crwdnd6555291:0{1}crwdnd6555291:0{3:N2}crwdne6555291:0.
        /// </summary>
        internal static string AttestCosts_SalaryAttested {
            get {
                return ResourceManager.GetString("AttestCosts_SalaryAttested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563468:0{0:N0}crwdnd6563468:0{1}crwdne6563468:0.
        /// </summary>
        internal static string AttestCosts_SalaryDeattested {
            get {
                return ResourceManager.GetString("AttestCosts_SalaryDeattested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563470:0crwdne6563470:0.
        /// </summary>
        internal static string AttestCosts_Warn_UninitializedBudget {
            get {
                return ResourceManager.GetString("AttestCosts_Warn_UninitializedBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556593:0{0}crwdne6556593:0.
        /// </summary>
        internal static string CreateInboundInvoice_Amount {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556594:0{0}crwdne6556594:0.
        /// </summary>
        internal static string CreateInboundInvoice_AmountVat {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_AmountVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556479:0crwdne6556479:0.
        /// </summary>
        internal static string CreateInboundInvoice_ButtonCreate {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555294:0crwdne6555294:0.
        /// </summary>
        internal static string CreateInboundInvoice_Description {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555295:0crwdne6555295:0.
        /// </summary>
        internal static string CreateInboundInvoice_HeaderInvoiceImage {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_HeaderInvoiceImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555296:0crwdne6555296:0.
        /// </summary>
        internal static string CreateInboundInvoice_HeaderPaymentDetails {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_HeaderPaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555297:0crwdne6555297:0.
        /// </summary>
        internal static string CreateInboundInvoice_Info {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555298:0crwdne6555298:0.
        /// </summary>
        internal static string CreateInboundInvoice_PageTitle {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555299:0crwdne6555299:0.
        /// </summary>
        internal static string CreateInboundInvoice_Reference {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555300:0crwdne6555300:0.
        /// </summary>
        internal static string CreateInboundInvoice_ReferenceAutomaticOcr {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_ReferenceAutomaticOcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555301:0crwdne6555301:0.
        /// </summary>
        internal static string CreateInboundInvoice_ReferenceManual {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_ReferenceManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555302:0{0:N0}crwdne6555302:0.
        /// </summary>
        internal static string CreateInboundInvoice_SuccessMessage {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555303:0crwdne6555303:0.
        /// </summary>
        internal static string CreateInboundInvoice_SupplierAccount {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_SupplierAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555304:0crwdne6555304:0.
        /// </summary>
        internal static string CreateInboundInvoice_UploadInvoiceImage {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_UploadInvoiceImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555305:0crwdne6555305:0.
        /// </summary>
        internal static string CreateInboundInvoice_ValidationError_Account {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_ValidationError_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556480:0{0}crwdne6556480:0.
        /// </summary>
        internal static string CreateInboundInvoice_ValidationError_Amount {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_ValidationError_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556481:0crwdne6556481:0.
        /// </summary>
        internal static string CreateInboundInvoice_ValidationError_Budget {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_ValidationError_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556482:0crwdne6556482:0.
        /// </summary>
        internal static string CreateInboundInvoice_ValidationError_Documents {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_ValidationError_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556483:0crwdne6556483:0.
        /// </summary>
        internal static string CreateInboundInvoice_ValidationError_MissingTag {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_ValidationError_MissingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556484:0crwdne6556484:0.
        /// </summary>
        internal static string CreateInboundInvoice_ValidationError_Purpose {
            get {
                return ResourceManager.GetString("CreateInboundInvoice_ValidationError_Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556600:0crwdne6556600:0.
        /// </summary>
        internal static string CreateOutboundInvoice_BoxTitle {
            get {
                return ResourceManager.GetString("CreateOutboundInvoice_BoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556671:0crwdne6556671:0.
        /// </summary>
        internal static string CreateOutboundInvoice_ButtonCreate {
            get {
                return ResourceManager.GetString("CreateOutboundInvoice_ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556602:0crwdne6556602:0.
        /// </summary>
        internal static string CreateOutboundInvoice_PageTitle {
            get {
                return ResourceManager.GetString("CreateOutboundInvoice_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556603:0{0:N0}crwdne6556603:0.
        /// </summary>
        internal static string CreateOutboundInvoice_SuccessMessage {
            get {
                return ResourceManager.GetString("CreateOutboundInvoice_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556697:0{0}crwdnd6556697:0{1}crwdne6556697:0.
        /// </summary>
        internal static string Donate_Explain {
            get {
                return ResourceManager.GetString("Donate_Explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556407:0{0}crwdnd6556407:0{1:N2}crwdnd6556407:0{2:N0}crwdne6556407:0.
        /// </summary>
        internal static string Donate_FundsReceived {
            get {
                return ResourceManager.GetString("Donate_FundsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556698:0{0}crwdne6556698:0.
        /// </summary>
        internal static string Donate_FundsReceivedLabel {
            get {
                return ResourceManager.GetString("Donate_FundsReceivedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556408:0{0}crwdne6556408:0.
        /// </summary>
        internal static string Donate_FundsReceivedNative {
            get {
                return ResourceManager.GetString("Donate_FundsReceivedNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556409:0crwdne6556409:0.
        /// </summary>
        internal static string Donate_Info {
            get {
                return ResourceManager.GetString("Donate_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556410:0crwdne6556410:0.
        /// </summary>
        internal static string Donate_PageTitle {
            get {
                return ResourceManager.GetString("Donate_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556411:0crwdne6556411:0.
        /// </summary>
        internal static string Donate_StatusInitial {
            get {
                return ResourceManager.GetString("Donate_StatusInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556412:0crwdne6556412:0.
        /// </summary>
        internal static string Donate_TransactionDetected {
            get {
                return ResourceManager.GetString("Donate_TransactionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556413:0{0}crwdne6556413:0.
        /// </summary>
        internal static string Donate_TxLabel {
            get {
                return ResourceManager.GetString("Donate_TxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556414:0{0}crwdne6556414:0.
        /// </summary>
        internal static string Donate_TxLabel_Loan {
            get {
                return ResourceManager.GetString("Donate_TxLabel_Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555306:0{0}crwdne6555306:0.
        /// </summary>
        internal static string FileExpenseClaim_Amount {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555307:0crwdne6555307:0.
        /// </summary>
        internal static string FileExpenseClaim_BankAccount {
            get {
                return ResourceManager.GetString("FileExpenseClaim_BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555308:0crwdne6555308:0.
        /// </summary>
        internal static string FileExpenseClaim_BankClearing {
            get {
                return ResourceManager.GetString("FileExpenseClaim_BankClearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555309:0crwdne6555309:0.
        /// </summary>
        internal static string FileExpenseClaim_BankName {
            get {
                return ResourceManager.GetString("FileExpenseClaim_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555310:0crwdne6555310:0.
        /// </summary>
        internal static string FileExpenseClaim_Budget {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556485:0crwdne6556485:0.
        /// </summary>
        internal static string FileExpenseClaim_ButtonRequest {
            get {
                return ResourceManager.GetString("FileExpenseClaim_ButtonRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555311:0crwdne6555311:0.
        /// </summary>
        internal static string FileExpenseClaim_CostType {
            get {
                return ResourceManager.GetString("FileExpenseClaim_CostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555312:0crwdne6555312:0.
        /// </summary>
        internal static string FileExpenseClaim_Description {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556737:0crwdne6556737:0.
        /// </summary>
        internal static string FileExpenseClaim_Expensify_CsvUploadDescription {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Expensify_CsvUploadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556756:0crwdne6556756:0.
        /// </summary>
        internal static string FileExpenseClaim_Expensify_Error_BadFile {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Expensify_Error_BadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556766:0crwdne6556766:0.
        /// </summary>
        internal static string FileExpenseClaim_Expensify_Error_InvalidCsv {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Expensify_Error_InvalidCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556757:0crwdne6556757:0.
        /// </summary>
        internal static string FileExpenseClaim_Expensify_Error_NeedsVat {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Expensify_Error_NeedsVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556738:0crwdne6556738:0.
        /// </summary>
        internal static string FileExpenseClaim_Expensify_InstructionsBasic {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Expensify_InstructionsBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556739:0{0}crwdne6556739:0.
        /// </summary>
        internal static string FileExpenseClaim_Expensify_InstructionsNeedVat {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Expensify_InstructionsNeedVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556740:0crwdne6556740:0.
        /// </summary>
        internal static string FileExpenseClaim_Expensify_InstructionsNothingAdvanced {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Expensify_InstructionsNothingAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556782:0crwdne6556782:0.
        /// </summary>
        internal static string FileExpenseClaim_Expensify_NeedBudgetsForAll {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Expensify_NeedBudgetsForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556783:0crwdne6556783:0.
        /// </summary>
        internal static string FileExpenseClaim_Expensify_NoRecordsLeft {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Expensify_NoRecordsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556741:0crwdne6556741:0.
        /// </summary>
        internal static string FileExpenseClaim_Expensify_ReportCurrency {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Expensify_ReportCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556784:0crwdne6556784:0.
        /// </summary>
        internal static string FileExpenseClaim_Expensify_SubmitRecordSingle {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Expensify_SubmitRecordSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556785:0{0}crwdne6556785:0.
        /// </summary>
        internal static string FileExpenseClaim_Expensify_SubmitRecordsSeveral {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Expensify_SubmitRecordsSeveral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556786:0crwdne6556786:0.
        /// </summary>
        internal static string FileExpenseClaim_Expensify_SuccessOne {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Expensify_SuccessOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556787:0{0}crwdne6556787:0.
        /// </summary>
        internal static string FileExpenseClaim_Expensify_SuccessSeveral {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Expensify_SuccessSeveral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556758:0crwdne6556758:0.
        /// </summary>
        internal static string FileExpenseClaim_Expensify_UploadAnother {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Expensify_UploadAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556759:0crwdne6556759:0.
        /// </summary>
        internal static string FileExpenseClaim_ForWhom_DefaultMyself {
            get {
                return ResourceManager.GetString("FileExpenseClaim_ForWhom_DefaultMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556760:0crwdne6556760:0.
        /// </summary>
        internal static string FileExpenseClaim_ForWhom_Prompt {
            get {
                return ResourceManager.GetString("FileExpenseClaim_ForWhom_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555313:0crwdne6555313:0.
        /// </summary>
        internal static string FileExpenseClaim_HeaderBankDetails {
            get {
                return ResourceManager.GetString("FileExpenseClaim_HeaderBankDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555314:0crwdne6555314:0.
        /// </summary>
        internal static string FileExpenseClaim_HeaderReceiptImages {
            get {
                return ResourceManager.GetString("FileExpenseClaim_HeaderReceiptImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555315:0crwdne6555315:0.
        /// </summary>
        internal static string FileExpenseClaim_Info {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555316:0crwdne6555316:0.
        /// </summary>
        internal static string FileExpenseClaim_PageTitle {
            get {
                return ResourceManager.GetString("FileExpenseClaim_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555317:0{0}crwdnd6555317:0{1:N2}crwdnd6555317:0{2}crwdne6555317:0.
        /// </summary>
        internal static string FileExpenseClaim_SuccessMessagePartOne {
            get {
                return ResourceManager.GetString("FileExpenseClaim_SuccessMessagePartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555318:0crwdne6555318:0.
        /// </summary>
        internal static string FileExpenseClaim_SuccessMessagePartTwo {
            get {
                return ResourceManager.GetString("FileExpenseClaim_SuccessMessagePartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555319:0crwdne6555319:0.
        /// </summary>
        internal static string FileExpenseClaim_SuccessMessagePartTwoOwnBudget {
            get {
                return ResourceManager.GetString("FileExpenseClaim_SuccessMessagePartTwoOwnBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556742:0crwdne6556742:0.
        /// </summary>
        internal static string FileExpenseClaim_Title_Expensify {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Title_Expensify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555320:0crwdne6555320:0.
        /// </summary>
        internal static string FileExpenseClaim_UploadRecieptImages {
            get {
                return ResourceManager.GetString("FileExpenseClaim_UploadRecieptImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555321:0{0}crwdne6555321:0.
        /// </summary>
        internal static string FileExpenseClaim_ValidationError_Amount {
            get {
                return ResourceManager.GetString("FileExpenseClaim_ValidationError_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555322:0crwdne6555322:0.
        /// </summary>
        internal static string FileExpenseClaim_ValidationError_Documents {
            get {
                return ResourceManager.GetString("FileExpenseClaim_ValidationError_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555323:0crwdne6555323:0.
        /// </summary>
        internal static string FileExpenseClaim_ValidationError_MissingTag {
            get {
                return ResourceManager.GetString("FileExpenseClaim_ValidationError_MissingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555324:0crwdne6555324:0.
        /// </summary>
        internal static string FileExpenseClaim_ValidationError_Purpose {
            get {
                return ResourceManager.GetString("FileExpenseClaim_ValidationError_Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556595:0{0}crwdne6556595:0.
        /// </summary>
        internal static string FileExpenseClaim_Vat {
            get {
                return ResourceManager.GetString("FileExpenseClaim_Vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556596:0crwdne6556596:0.
        /// </summary>
        internal static string ListInboundInvoices_Header {
            get {
                return ResourceManager.GetString("ListInboundInvoices_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556597:0crwdne6556597:0.
        /// </summary>
        internal static string ListInboundInvoices_Header_Sender {
            get {
                return ResourceManager.GetString("ListInboundInvoices_Header_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556598:0crwdne6556598:0.
        /// </summary>
        internal static string ListInboundInvoices_Info {
            get {
                return ResourceManager.GetString("ListInboundInvoices_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556599:0crwdne6556599:0.
        /// </summary>
        internal static string ListInboundInvoices_Title {
            get {
                return ResourceManager.GetString("ListInboundInvoices_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556708:0crwdne6556708:0.
        /// </summary>
        internal static string ListOutboundInvoices_CreatedDateTime {
            get {
                return ResourceManager.GetString("ListOutboundInvoices_CreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556709:0crwdne6556709:0.
        /// </summary>
        internal static string ListOutboundInvoices_CustomerReceivingInvoice {
            get {
                return ResourceManager.GetString("ListOutboundInvoices_CustomerReceivingInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556710:0crwdne6556710:0.
        /// </summary>
        internal static string ListOutboundInvoices_Header {
            get {
                return ResourceManager.GetString("ListOutboundInvoices_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556711:0crwdne6556711:0.
        /// </summary>
        internal static string ListOutboundInvoices_Info {
            get {
                return ResourceManager.GetString("ListOutboundInvoices_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556712:0crwdne6556712:0.
        /// </summary>
        internal static string ListOutboundInvoices_InvoiceAmountTotalIncludingTaxes {
            get {
                return ResourceManager.GetString("ListOutboundInvoices_InvoiceAmountTotalIncludingTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556713:0crwdne6556713:0.
        /// </summary>
        internal static string ListOutboundInvoices_PaymentExpectedByDate {
            get {
                return ResourceManager.GetString("ListOutboundInvoices_PaymentExpectedByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556714:0crwdne6556714:0.
        /// </summary>
        internal static string ListOutboundInvoices_Title {
            get {
                return ResourceManager.GetString("ListOutboundInvoices_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563584:0crwdne6563584:0.
        /// </summary>
        internal static string PayOutMoney_AutomationFieldNext {
            get {
                return ResourceManager.GetString("PayOutMoney_AutomationFieldNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563586:0crwdne6563586:0.
        /// </summary>
        internal static string PayOutMoney_AutomationFieldStart {
            get {
                return ResourceManager.GetString("PayOutMoney_AutomationFieldStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555325:0crwdne6555325:0.
        /// </summary>
        internal static string PayOutMoney_GridHeader_Amount {
            get {
                return ResourceManager.GetString("PayOutMoney_GridHeader_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563568:0crwdne6563568:0.
        /// </summary>
        internal static string PayOutMoney_GridHeader_CurrencyMethod {
            get {
                return ResourceManager.GetString("PayOutMoney_GridHeader_CurrencyMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555329:0crwdne6555329:0.
        /// </summary>
        internal static string PayOutMoney_GridHeader_PaidOut {
            get {
                return ResourceManager.GetString("PayOutMoney_GridHeader_PaidOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563570:0crwdne6563570:0.
        /// </summary>
        internal static string PayOutMoney_GridHeader_PayThis {
            get {
                return ResourceManager.GetString("PayOutMoney_GridHeader_PayThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555330:0crwdne6555330:0.
        /// </summary>
        internal static string PayOutMoney_GridHeader_Recipient {
            get {
                return ResourceManager.GetString("PayOutMoney_GridHeader_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555331:0crwdne6555331:0.
        /// </summary>
        internal static string PayOutMoney_GridHeader_Reference {
            get {
                return ResourceManager.GetString("PayOutMoney_GridHeader_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555332:0crwdne6555332:0.
        /// </summary>
        internal static string PayOutMoney_Header {
            get {
                return ResourceManager.GetString("PayOutMoney_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555333:0crwdne6555333:0.
        /// </summary>
        internal static string PayOutMoney_Info {
            get {
                return ResourceManager.GetString("PayOutMoney_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563572:0crwdne6563572:0.
        /// </summary>
        internal static string PayOutMoney_Modal_ConfirmPaid {
            get {
                return ResourceManager.GetString("PayOutMoney_Modal_ConfirmPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563574:0crwdne6563574:0.
        /// </summary>
        internal static string PayOutMoney_Modal_CurrencyAmount {
            get {
                return ResourceManager.GetString("PayOutMoney_Modal_CurrencyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563576:0crwdne6563576:0.
        /// </summary>
        internal static string PayOutMoney_Modal_Header {
            get {
                return ResourceManager.GetString("PayOutMoney_Modal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563578:0crwdne6563578:0.
        /// </summary>
        internal static string PayOutMoney_Modal_LabelOcr1 {
            get {
                return ResourceManager.GetString("PayOutMoney_Modal_LabelOcr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563580:0crwdne6563580:0.
        /// </summary>
        internal static string PayOutMoney_Modal_LabelOcr2 {
            get {
                return ResourceManager.GetString("PayOutMoney_Modal_LabelOcr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563582:0crwdne6563582:0.
        /// </summary>
        internal static string PayOutMoney_Modal_TransferMethod {
            get {
                return ResourceManager.GetString("PayOutMoney_Modal_TransferMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556443:0crwdne6556443:0.
        /// </summary>
        internal static string PayoutMoney_OptionShowOcr {
            get {
                return ResourceManager.GetString("PayoutMoney_OptionShowOcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555892:0{0:N0}crwdne6555892:0.
        /// </summary>
        internal static string PayOutMoney_OptionShowOpen {
            get {
                return ResourceManager.GetString("PayOutMoney_OptionShowOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555334:0crwdne6555334:0.
        /// </summary>
        internal static string PayOutMoney_PageTitle {
            get {
                return ResourceManager.GetString("PayOutMoney_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563588:0crwdne6563588:0.
        /// </summary>
        internal static string PayOutMoney_PaymentLate {
            get {
                return ResourceManager.GetString("PayOutMoney_PaymentLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555335:0#{0}crwdne6555335:0.
        /// </summary>
        internal static string PayOutMoney_PayoutCannotUndo {
            get {
                return ResourceManager.GetString("PayOutMoney_PayoutCannotUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555336:0{0:N0}crwdnd6555336:0{1}crwdne6555336:0.
        /// </summary>
        internal static string PayOutMoney_PayoutCreated {
            get {
                return ResourceManager.GetString("PayOutMoney_PayoutCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555337:0{0:N0}crwdne6555337:0.
        /// </summary>
        internal static string PayOutMoney_PayoutUndone {
            get {
                return ResourceManager.GetString("PayOutMoney_PayoutUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555634:0crwdne6555634:0.
        /// </summary>
        internal static string PayrollTaxForms_AdditiveTax {
            get {
                return ResourceManager.GetString("PayrollTaxForms_AdditiveTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555635:0crwdne6555635:0.
        /// </summary>
        internal static string PayrollTaxForms_DeductedTax {
            get {
                return ResourceManager.GetString("PayrollTaxForms_DeductedTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555636:0crwdne6555636:0.
        /// </summary>
        internal static string PayrollTaxForms_GrossPay {
            get {
                return ResourceManager.GetString("PayrollTaxForms_GrossPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555637:0crwdne6555637:0.
        /// </summary>
        internal static string PayrollTaxForms_Info {
            get {
                return ResourceManager.GetString("PayrollTaxForms_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555638:0crwdne6555638:0.
        /// </summary>
        internal static string PayrollTaxForms_PageTitle {
            get {
                return ResourceManager.GetString("PayrollTaxForms_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555639:0{0}crwdne6555639:0.
        /// </summary>
        internal static string PayrollTaxForms_TaxFormsHeader {
            get {
                return ResourceManager.GetString("PayrollTaxForms_TaxFormsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555640:0crwdne6555640:0.
        /// </summary>
        internal static string PayrollTaxForms_TotalCost {
            get {
                return ResourceManager.GetString("PayrollTaxForms_TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555641:0crwdne6555641:0.
        /// </summary>
        internal static string PayrollTaxForms_TotalTax {
            get {
                return ResourceManager.GetString("PayrollTaxForms_TotalTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555338:0{0}crwdne6555338:0.
        /// </summary>
        internal static string RequestCashAdvance_Amount {
            get {
                return ResourceManager.GetString("RequestCashAdvance_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555339:0crwdne6555339:0.
        /// </summary>
        internal static string RequestCashAdvance_BankAccount {
            get {
                return ResourceManager.GetString("RequestCashAdvance_BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555340:0crwdne6555340:0.
        /// </summary>
        internal static string RequestCashAdvance_BankClearing {
            get {
                return ResourceManager.GetString("RequestCashAdvance_BankClearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555341:0crwdne6555341:0.
        /// </summary>
        internal static string RequestCashAdvance_BankName {
            get {
                return ResourceManager.GetString("RequestCashAdvance_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555342:0crwdne6555342:0.
        /// </summary>
        internal static string RequestCashAdvance_Budget {
            get {
                return ResourceManager.GetString("RequestCashAdvance_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6556486:0crwdne6556486:0.
        /// </summary>
        internal static string RequestCashAdvance_ButtonRequest {
            get {
                return ResourceManager.GetString("RequestCashAdvance_ButtonRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555343:0crwdne6555343:0.
        /// </summary>
        internal static string RequestCashAdvance_HeaderBankDetails {
            get {
                return ResourceManager.GetString("RequestCashAdvance_HeaderBankDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555344:0crwdne6555344:0.
        /// </summary>
        internal static string RequestCashAdvance_Info {
            get {
                return ResourceManager.GetString("RequestCashAdvance_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555345:0crwdne6555345:0.
        /// </summary>
        internal static string RequestCashAdvance_PageTitle {
            get {
                return ResourceManager.GetString("RequestCashAdvance_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555346:0crwdne6555346:0.
        /// </summary>
        internal static string RequestCashAdvance_Purpose {
            get {
                return ResourceManager.GetString("RequestCashAdvance_Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555347:0{0}crwdnd6555347:0{2}crwdnd6555347:0{3:N2}crwdne6555347:0.
        /// </summary>
        internal static string RequestCashAdvance_SuccessMessagePartOne {
            get {
                return ResourceManager.GetString("RequestCashAdvance_SuccessMessagePartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555348:0crwdne6555348:0.
        /// </summary>
        internal static string RequestCashAdvance_SuccessMessagePartTwo {
            get {
                return ResourceManager.GetString("RequestCashAdvance_SuccessMessagePartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555349:0crwdne6555349:0.
        /// </summary>
        internal static string RequestCashAdvance_SuccessMessagePartTwoOwnBudget {
            get {
                return ResourceManager.GetString("RequestCashAdvance_SuccessMessagePartTwoOwnBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555350:0{0}crwdne6555350:0.
        /// </summary>
        internal static string RequestCashAdvance_ValidationError_Amount {
            get {
                return ResourceManager.GetString("RequestCashAdvance_ValidationError_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555351:0crwdne6555351:0.
        /// </summary>
        internal static string RequestCashAdvance_ValidationError_BankAccount {
            get {
                return ResourceManager.GetString("RequestCashAdvance_ValidationError_BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555352:0crwdne6555352:0.
        /// </summary>
        internal static string RequestCashAdvance_ValidationError_BankClearing {
            get {
                return ResourceManager.GetString("RequestCashAdvance_ValidationError_BankClearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555353:0crwdne6555353:0.
        /// </summary>
        internal static string RequestCashAdvance_ValidationError_BankName {
            get {
                return ResourceManager.GetString("RequestCashAdvance_ValidationError_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555354:0crwdne6555354:0.
        /// </summary>
        internal static string RequestCashAdvance_ValidationError_Budget {
            get {
                return ResourceManager.GetString("RequestCashAdvance_ValidationError_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555355:0crwdne6555355:0.
        /// </summary>
        internal static string RequestCashAdvance_ValidationError_Purpose {
            get {
                return ResourceManager.GetString("RequestCashAdvance_ValidationError_Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555356:0crwdne6555356:0.
        /// </summary>
        internal static string ValidateReceipts_Header_ReceiptsAwaitingValidation {
            get {
                return ResourceManager.GetString("ValidateReceipts_Header_ReceiptsAwaitingValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555357:0crwdne6555357:0.
        /// </summary>
        internal static string ValidateReceipts_Info {
            get {
                return ResourceManager.GetString("ValidateReceipts_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555358:0crwdne6555358:0.
        /// </summary>
        internal static string ValidateReceipts_PageTitle {
            get {
                return ResourceManager.GetString("ValidateReceipts_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6563472:0{0:N0}crwdnd6563472:0{1}crwdnd6563472:0{2:N2}crwdne6563472:0.
        /// </summary>
        internal static string ValidateReceipts_ReceiptsDevalidated {
            get {
                return ResourceManager.GetString("ValidateReceipts_ReceiptsDevalidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crwdns6555360:0{0:N0}crwdnd6555360:0{1}crwdnd6555360:0{2:N2}crwdne6555360:0.
        /// </summary>
        internal static string ValidateReceipts_ReceiptsValidated {
            get {
                return ResourceManager.GetString("ValidateReceipts_ReceiptsValidated", resourceCulture);
            }
        }
    }
}
